wmde/wbaas-deploy

- k8s/helmfile/helmfile.yaml
> Local+Staging: Use UI 0.3.0 chart version

- k8s/helmfile/helmfile.yaml
> Local+staging: Use queryservice 0.2.0

- k8s/helmfile/helmfile.yaml
> Local+staging: Use queryservice UI 0.2.0

- k8s/helmfile/helmfile.yaml
> prod: Bump queryservice-ui to 0.2.0

- k8s/helmfile/helmfile.yaml
> prod: Bump queryservice to 0.2.0

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T322127
> staging & local: use API chart v0.20.0

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T322127
> production: use API chart v0.20.0

- doc/tools.md
I wrote documentation for some useful k8s tools
> Add tools.md

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Prod: Update UI image version

- tf/env/staging/buckets.tf
This deploys tf-module-buckets-2 to staging, which adds a retention policy for the backup buckets
https://phabricator.wikimedia.org/T321091
> staging: use tf-module-buckets-2

- tf/env/staging/buckets.tf
This reverts commit cb806ca93a6844190a8f5bbb52594ef17c58ea4d.
> Revert "staging: use tf-module-buckets-2 (#609)"

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Bump follow-redirects from 1.13.2 to 1.15.2

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Bump vuetify from 2.5.10 to 2.6.13

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Depends on https://github.com/wbstack/charts/pull/110
> staging & local: deploy api chart 0.20.1

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Staging: Bump minimist from 1.2.5 to 1.2.7

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Prod: Bump minimist from 1.2.5 to 1.2.7

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Staging: Bump actions/cache from 3.0.8 to 3.2.0 on UI

- k8s/helmfile/env/production/private.yaml
> k8s: prod: increase sql storage size to 120GB

- k8s/helmfile/env/production/private.yaml
Reverts wmde/wbaas-deploy#637
Let's try this again but remove the StatefulSet before applying this.
> Revert "Revert "k8s: prod: increase sql storage size to 120GB""

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Staging+Local: Bump decode-uri-component from 0.2.0 to 0.2.2

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Production: Bump decode-uri-component from 0.2.0 to 0.2.2

- tf/env/production/variables.tf
- tf/env/staging/variables.tf
Bug: [T326131](https://phabricator.wikimedia.org/T326131)
> tf: Add Andrew as a terraformer

- tf/env/production/variables.tf
- tf/env/staging/variables.tf
As proposed by @tarrow via email, this adds myself to the list of "terraformers", granting access to the terraform state bucket.
> tf: add frederik.ring to terraformers

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> staging+local: Bump UI core-js from 3.18.0 to 3.27.1

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Revert "Production: Bump UI core-js from 3.18.0 to 3.27.1"

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Revert "Revert "Production: Bump UI core-js from 3.18.0 to 3.27.1""

- k8s/helmfile/env/local/mediawiki-137-fp.values.yaml.gotmpl
- k8s/helmfile/env/staging/mediawiki-137-fp.values.yaml.gotmpl
Bug: [T322665](https://phabricator.wikimedia.org/T322665)
> staging+local: Bump MediaWiki to 1.37-7.4-20230112-fp-beta-0

- k8s/helmfile/env/common/ui.values.yaml.gotmpl
- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/production/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
Refactors the YAML value files for UI deployments and adds a `common` file with shared values.
diffs are clean for staging & prod.
>  refactor (helm): ui values are repeated across envs

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
> Staging+local: Adjust Log in page

- k8s/helmfile/env/production/ui.values.yaml.gotmpl
> Prod: Adjust Log in page

- doc/adr/0003-number-of-clusters.md
- doc/adr/0004-no-new-chart-for-image-bumps.md
- doc/adr/0006-helmfile-base-values.md
- doc/adr/NNNN-adr-template.md
- doc/adr/index.md
- doc/adr/update-toc
Ticket [T326643](https://phabricator.wikimedia.org/T326643).
As discussed earlier, this adds an ADR about how to handle Helmfile values in the future.
I also added a script that creates a TOC for us automatically.
> docs(adr): describe "production as base case" setup for helmfile values

- tf/env/staging/cluster.tf
Ticket: https://phabricator.wikimedia.org/T328564
> feat(staging-cluster): add 3 additional n2-standard-4 nodes to k8s cluster

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T328567
Currently diffs with
```diff
automountServiceAccountToken: true                                                                                                                                                         [22/692]
affinity:                                                                                                                                                                                          
podAntiAffinity:                                                                                                                                                                                 
-           preferredDuringSchedulingIgnoredDuringExecution: …
```
> feat(es-staging): set anti-affinity to hard

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T328740
> feat(es-staging): increasing number of concurrent recoveries should speed up node recovery

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Tciket: https://phabricator.wikimedia.org/T328740
> feat(es-staging): increasing number of allowed primary recoveries should decrease downtime

- tf/env/production/cluster.tf
Ticket https://phabricator.wikimedia.org/T328553
> feat(cluster-production): add 3 n2-highmem-16 nodes to node pool

- tf/env/production/cluster.tf
> fix(tf-production): fix duplicate node pool name

- k8s/helmfile/env/production/elasticsearch.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T328553
The current node pool should be able to provide what is requested here, looking at the stats:
> feat(es-production): adjust elasticsearch settings to make use of scaled up hardware

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
#721 somehow silenced all logging. Giving it another try as described here: https://stackoverflow.com/a/65181735/797194
> chore(staging-es): try different approach of arriving at debug log level

- doc/tools.md
I think it's a useful mention, what do y'all think?
> Add kubie docs to doc/tools.md

- k8s/helmfile/env/local/kube-prometheus-stack.values.yaml.gotmpl
- k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl
- k8s/helmfile/env/staging/kube-prometheus-stack.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
- k8s/helmfile/prometheus-operator.yaml
Following this guide: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged
> Add self-deployed collection of Prometheus data in staging

- tf/env/production/cluster.tf
> feat(monitoring): enable managed prometheus in production

- k8s/helmfile/helmfile.yaml
- k8s/helmfile/prometheus-operator.yaml
Production equivalent of #742 
Depends on #748
> feat(monitoring): deploy kube-prometheus-stack to production

- k8s/helmfile/helmfile.yaml
Production equivalent of #743 
Depends on #749
> feat(monitoring): deploy prometheus-elasticsearch-exporter to production

- k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl
Fixup for #759 
Reference: https://github.com/prometheus-community/helm-charts/issues/3005#issuecomment-1422319126
> chore(monitoring): grafana should limit resource usage

- doc/adr/0007-monitoring-prometheus.md
- doc/adr/index.md
This collects some of the decisions that were made along the way while setting up our Prometheus based monitoring.
> docs(adr): document prometheus setup

- doc/adr/0008-service-mesh.md
- doc/adr/index.md
Ticket [T330862](https://phabricator.wikimedia.org/T330862)
> docs(adr): propose adopting an istio service mesh

- charts/stats-cron/.helmignore
- charts/stats-cron/Chart.yaml
- charts/stats-cron/templates/job.yaml
- charts/stats-cron/values.yaml
- k8s/helmfile/helmfile.yaml
- tf/env/production/elasticsearch-monitoring-dashboard.tf
- tf/env/production/monitoring.tf
> Revert "chore(monitoring): stats-cron resources are not in use anymore"

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T330863
> chore(monitoring): label es pods to trigger istio sidecar injection

- k8s/helmfile/env/local/elasticsearch.values.yaml.gotmpl
- k8s/helmfile/env/production/elasticsearch.values.yaml.gotmpl
- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Requires #779 
Ticket https://phabricator.wikimedia.org/T330863
> feat(monitoring): inject istio sidecar for elasticsearch in all environments

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T305932
> chore(api): bump version to 8x.9.12 in local and staging

- k8s/helmfile/env/production/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T305932
> chore(api): bump version to 8x.9.12 in production

- doc/README.md
- doc/querying-prometheus.md
Wrapping up the topic for now, this is a small doc that hopefully helps others on the team get started with finding relevant metrics we now collect.
> Add document on basic PromQL Metrics Explorer queries

- k8s/helmfile/env/production/mediawiki-138.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/mediawiki-138.values.yaml.gotmpl
- k8s/helmfile/env/staging/platform-nginx.nginx.conf
- k8s/helmfile/env/staging/platform-nginx.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket: https://phabricator.wikimedia.org/T331854
> feat(mediawiki): add 1.38 canary deployment for select domains

- k8s/helmfile/env/staging/mediawiki-137-fp.values.yaml.gotmpl
- k8s/helmfile/env/staging/platform-nginx.nginx.conf
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T331854
> feat(mediawiki): use version 1.38 throughout in staging

- k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
This would be an alternative to #832 as per the docs here: https://www.elastic.co/guide/en/cloud-on-k8s/2.2/k8s-service-mesh-istio.html
> fix(elasticsearch): try using rules from es docs in staging

- doc/tools.md
Adds some documentation for using http://www.elastichq.org/
> docs: Add ElasticHQ to tools.md

- tf/env/production/es-prometheus-dashoard.tf
Imports the cloned ElasticSearch dashboard into Terraform.
Ticket https://phabricator.wikimedia.org/T334186
> chore(tf): import elastic search production dashboard

- k8s/helmfile/env/production/platform-nginx.nginx.conf
Undoing changes from #855 in batches.
> chore(nginx): point batch of 5 wikis towards 1.39 release

- k8s/helmfile/env/production/platform-nginx.nginx.conf
Undoing changes from #855 in batches.
> chore(nginx): point batch of 7 wikis towards 1.39 release

- k8s/helmfile/env/production/platform-nginx.nginx.conf
Undoing changes from https://github.com/wmde/wbaas-deploy/pull/855 in batches.
> chore(nginx): point batch of 10 wikis towards 1.39 release

- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T327646
> chore(mediawiki): uninstall 1.38 release

- tf/env/production/metric-alarms.tf
- tf/env/production/monitoring.tf
- tf/env/staging/metric-alarms.tf
- tf/env/staging/monitoring.tf
- tf/modules/CHANGELOG.md
Adds staging and production alarms as introduced in #876
> feat(monitoring): add alerting policy for es cluster health

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
- tf/modules/CHANGELOG.md
Applying the changes from #880
> chore(tf): use updated monitoring module

- k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
prod counterpart to https://github.com/wmde/wbaas-deploy/pull/882
> prod: use mw 1.39-7.4-20230426-0

- README.md
Make README more useful to external people rather than just be useful to internal WMDE users
> docs: add more explanation to README for newcomers

- k8s/helmfile/env/local/sql.values.yaml.gotmpl
- k8s/helmfile/env/production/sql.values.yaml.gotmpl
- k8s/helmfile/env/staging/sql.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T334110
> chore(sql): bump resource limits, use same values for limits and requests throughout

- k8s/helmfile/env/production/sql.values.yaml.gotmpl
> fix(sql): lower production limits to match available resources

- k8s/helmfile/env/production/sql.values.yaml.gotmpl
> Revert "fix(sql): lower production limits to match available resources"

- k8s/helmfile/env/production/sql.values.yaml.gotmpl
> Revert "Revert "chore(sql): set production replica count to 0""

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
- tf/env/production/kubernetes-secrets.tf
- tf/env/production/namespaces.tf
Ticket https://phabricator.wikimedia.org/T330389
> feat: deploy mediawiki job queue to production

- k8s/helmfile/env/production/redis.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T338928
> chore(redis): raise limits/requests for both primary and replicas

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T339071
Requires https://github.com/wbstack/api/pull/611
> chore(api): scale down replicas, update api image

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T339071
Requires https://github.com/wbstack/api/pull/612
> chore(api): bump image version to remove temporary short circuit in jobs

- k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T339903
> fix(sql-backup): system cannot handle number of log lines in verbose mode

- tf/env/production/platform-summary-dashboard.tf
- tf/env/staging/platform-summary-dashboard.tf
Ticket: https://phabricator.wikimedia.org/T335961
Fixup for #970
---
We also still need to change the aligner function it seems.
> fix(platform-summary): use align_delta instead of mean

- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T335853
This would supersede #980 as the cluster now has enough resources (#985)
> chore(staging): add bitnami based elasticsearch cluster

- bin/local/README.md
- bin/local/create-local-user.sh
- bin/local/create-local-wiki.sh
In order to create a whole load of wikis locally (https://phabricator.wikimedia.org/T335960) I created this script. Also improved `create-local-user.sh` because I found out about [jo](https://jpmens.net/2016/03/05/a-shell-command-to-create-json-jo/)
> local script: Add `create-local-wiki.sh`

- k8s/helmfile/env/staging/api.values.yaml.gotmpl
This reverts commit c43a7935daf355b06bd7b7d53ca115bae75cab5c.
> Revert "Revert "chore(api): enable stackdriver for staging api (#1018)" (#1019)"

- tf/env/production/cluster.tf
> feat(cluster): update logging variant for production

- tf/env/production/cluster.tf
> chore(cluster): double production disk size

- Makefile
cleaning up a leftover Makefile target
> chore(makefile): Remove skaffold mediawiki-138 target

- k8s/jobs/elasticSearchInitJob.sh
- k8s/jobs/elasticSearchInitJob.yaml
Ticket https://phabricator.wikimedia.org/T335891
Requires #1065
> feat(k8s): add elasticsearch init job

- k8s/helmfile/helmfile.yaml
Applying the fix from https://github.com/wbstack/charts/pull/124
> chore(helmfile): bump mediawiki chart version

- tf/env/production/namespaces.tf
- tf/env/staging/namespaces.tf
> fix: fix typo in namespace metadata

- tf/env/production/namespaces.tf
> fix: fix typo in provider

- k8s/helmfile/env/local/wbaas-backup.values.yaml.gotmpl
- k8s/helmfile/env/staging/wbaas-backup.values.yaml.gotmpl
> chore(backup): bump image version in local and staging

- k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
> chore(backup): update production setup to use s3 based transfer

- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
I mixed up the values for production and staging.
> fix(api): pod ip ranges are incorrect

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Adjustment for the upcoming API chart https://github.com/wbstack/charts/pull/126
Needed for testing https://github.com/wbstack/api/pull/626
> chore(staging/local): change api values for recaptcha

- k8s/helmfile/istio-control-plane.yaml
Previously we did not define a chart version here and this got us a surprise upgrade
> chore(istio): add chart version

- k8s/helmfile/env/production/api.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1161
> Revert "fix: decrease signup limit from 50 to 10 per day"

- bin/local/README.md
- bin/local/create-local-user.sh
- bin/local/new-local-cluster.sh
Since ReCaptcha is now even on local env functional, the convenience script to create a new local user needed to be changed (as it relied on not using a valid recaptcha response)
Also the script for unattended local cluster re-creation was improved (and rephrased) a little bit
> fix(local): fix & improve local dev scripts

- tf/env/production/cluster.tf
https://phabricator.wikimedia.org/T348148
In an attempt to fix the logical backups, this should fix the problem in case we run out of disk space
> chore(prod): increase disk size (ephemeral storage)

- tf/env/staging/monitoring.tf
Deploys tf-module-monitoring-20 to staging
PR of v20: https://github.com/wmde/wbaas-deploy/pull/1185
> chore(deploy): staging: tf-module-monitoring-20

- k8s/helmfile/helmfile.yaml
Bug: https://phabricator.wikimedia.org/T335853
> chore(k8s): add bitnami based production elasticsearch cluster

- tf/env/production/namespaces.tf
Still seeing many timeouts with 4 pods in parallel
> prod: reduce adhoc-jobs pod limit to 1

- k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
> prod: increase mw-web memory limit

- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
The updater is currently repeatedly crashing (`OOMKilled`) while trying to process a big batch
```
09:25:14.471 [main] INFO  o.w.query.rdf.tool.WbStackUpdate - Starting Updater 0.3.84 (3bcfddc0f526c9a227773e68fe29419343d33993) --wikibaseHost osloddt.wikibase.cloud --ids Q1338147,Q1338148,Q1338149,Q1338122,Q1338123,Q1338124,Q1338125,Q1338126,Q1338127,Q1338128,Q1338129,Q1338130,Q1338131,Q1338132,Q1338133,Q1338134,Q1338135,Q1338136,Q1338137,Q1338138,Q1338139,Q1338140,Q1338141,Q1338142,Q1338143,Q1338144,Q1338145,Q1338146,Q1338117,Q1338118,Q1338119,Q1338120,Q1338121,Q1338091,Q1338092,Q1338093,Q1338094,Q1338095,Q1338096,Q1338097,Q1338098,Q1338099,Q1338100,Q1338101,Q1338102,Q1338103,Q1338104,Q1338105,Q1338106,Q1338107,Q1338108,Q1338109,Q1338110,Q1338111,Q1338112,Q1338113,Q1338114,Q1338115,Q133811 …
```
> fix(queryservice-updater): raise memory limits

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
https://github.com/wmde/wbaas-deploy/pull/1231
> use tf-module-monitoring-21 on prod & stagin

- k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
This bot is causing a lot of traffic in the last few days for no known reason. It seems it's at least semi-shady:
- https://community.cloudflare.com/t/getting-tons-of-bad-bots-attack-recently/578502/4
- https://udger.com/resources/ua-list/bot-detail?bot=thesis-research-bot
> chore(ingress): block traffic from thesis-research-bot

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
deploys tf-module-monitoring-22 #1265
(adjustment to logical sql backup alerting policy)
> deploy tf-module-monitoring-22

- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T348256
> Deploy 3 queryservice-updater replicas

- k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1305
> Revert "Change cronSchedule for testing if SQL backups still works"

- tf/env/local/namespaces.tf
- tf/env/production/namespaces.tf
- tf/env/staging/namespaces.tf
Ticket https://phabricator.wikimedia.org/T352657
Connects https://github.com/wbstack/api/pull/701
> feat(k8s): add namespace for running queryservice jobs

- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
Includes https://github.com/wbstack/queryservice-updater/pull/144
> chore: update queryservice-updater

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T352662
> feat(staging): deploy two named laravel queue workers

- k8s/helmfile/helmfile.yaml
Fixes https://github.com/wbstack/charts/pull/135
> chore(helmfile): bump api chart in staging and local

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T352009
> feat(api): deploy additional api-queue for manual intervention

- k8s/helmfile/env/production/elasticsearch-1.values.yaml.gotmpl
> production: increase memory for elasticsearch masters

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/local/minio.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
- tf/env/local/config-map.tf
Ticket https://phabricator.wikimedia.org/T354744
> feat(api): configure local and staging to store api assets using S3 protocol

- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T354744
> chore(production): switch api to use s3 storage driver

- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Reverts wmde/wbaas-deploy#1358
> Revert "chore(production): switch api to use s3 storage driver"

- tf/modules/CHANGELOG.md
- tf/modules/buckets/main.tf
Picks up the concerns raised in https://github.com/wmde/wbaas-deploy/pull/1366/files#r1459448941
> feat: add iam members and hmac keys for static assets in module

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
- tf/env/staging/buckets.tf
- tf/env/staging/secrets-gcs.tf
Ticket https://phabricator.wikimedia.org/T354286
Requires https://github.com/wbstack/api/pull/727
> chore(local+staging): use dedicated gcs hmac key for platform api

- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
- tf/env/production/buckets.tf
Ticket https://phabricator.wikimedia.org/T354744
Follows up on https://github.com/wmde/wbaas-deploy/pull/1358
> feat: use s3 based storage driver for api in production

- k8s/helmfile/env/local/queryservice-ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice-ui.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T347023
Deploys https://github.com/wbstack/queryservice-ui/pull/237
> chore(qs-ui): update image to 1.5 in staging and local

- k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
I would like to use this pod to create the dump for https://phabricator.wikimedia.org/T355801
> chore(production): enable restore pod for wbaas-backup

- tf/env/staging/monitoring.tf
Ships #1414 to staging.
Ticket https://phabricator.wikimedia.org/T356254
> chore(tf): update monitoring module in staging

- tf/env/production/monitoring.tf
Ships #1414 to production.
Ticket https://phabricator.wikimedia.org/T356254
> chore(tf): update monitoring module in production

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
deploys api 9x.1.0 to staging & local
> chore(api): staging/local 9x.1.0

- k8s/helmfile/env/local/tool-widar.values.yaml.gotmpl
- k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T350469
> chore: bump tool-widar image

- k8s/helmfile/env/local/tool-widar.values.yaml.gotmpl
- k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl
- k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T350469
> chore: bump tool-widar image in production

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T342866
Requires: https://github.com/wbstack/charts/pull/138 https://github.com/wbstack/api/pull/753
> chore(api): update chart and use horizon in staging and local

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T342866
> chore(api): update chart in local and staging to include service monitor object

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T342866
> Configure horizon queue supervisor for production

- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/production/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1504
> Revert "Configure horizon queue supervisor for production"

- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1514
> Revert "production: reduce queryservice-updater replica 0"

- k8s/helmfile/env/production/queryservice-gateway.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T361551
> chore(qs-gateway): update image to 2.3 in production

- k8s/helmfile/env/local/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T361436
> chore(wdqs): bump image version in local and staging

- tf/modules/CHANGELOG.md
- tf/modules/monitoring/metric-alarms.tf
Ticket https://phabricator.wikimedia.org/T361836
Requires: https://github.com/wbstack/api/pull/780
> feat(monitoring): add alarm on high number of pending qs batches

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
Ticket https://phabricator.wikimedia.org/T361836
Currently diffs like:
```
OpenTofu will perform the following actions:                                                                                                                                                                
+ resource "google_monitoring_alert_policy" "alert_policy_prometheus_metric" {                                                                                                                            
+ combiner              = "OR"                                                                                                                                                                        
+ creation_record       = (known after apply) …
```
> chore(tf): bump monitoring module to include qs batches alarm

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
Reverts wmde/wbaas-deploy#1526
> Revert "chore(tf): bump monitoring module to include qs batches alarm"

- tf/modules/monitoring/metric-alarms.tf
Ticket: https://phabricator.wikimedia.org/T361836
> fix: metric name is misspelled

- tf/env/production/monitoring.tf
- tf/env/staging/monitoring.tf
Reverts wmde/wbaas-deploy#1527
> Revert "Revert "chore(tf): bump monitoring module to include qs batches alarm""

- k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T361436
> chore(wdqs): update version running in production

- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1534
> Revert "chore(queryservice-updater): temporarily scale down to 0"

- k8s/helmfile/env/local/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T362617
> chore(wdqs): use 0.3.137-wbstack.1 in staging and local

- k8s/helmfile/env/local/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T361551#9719481
> chore(queryservice): update image version to 0.3.135-wbstack.2 in staging and local

- k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T361551#9719481
> chore(queryservice): update image version to 0.3.135-wbstack.2 in production

- tf/env/staging/kubernetes-secrets.tf
- tf/env/staging/secrets-api.tf
This is a noop, preparing for rotation of the keys.
> chore(api/staging): rename oauth key to prepare for rotation

- tf/env/staging/kubernetes-secrets.tf
- tf/env/staging/secrets-api.tf
This replaces the OAuth keys used in staging.
> chore(api/staging): rotate oauth keys

- tf/env/production/kubernetes-secrets.tf
- tf/env/production/secrets-api.tf
This PR should finish off the migration to cookie based auth as per https://phabricator.wikimedia.org/T363100
> chore(api,production): rotate oauth keys

- doc/debugging-queryservice-backpressure.md
I could go into much further detail here, but I feel that might stop being helpful and start being confusing.
Maybe an unbiased reviewer can rate this doc on a helpfulness scale so I can extend / shrink it accordingly.
> docs: document queryservice pipeline and debugging approaches

- k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T365916
> chore(quickstatements): update image version in production

- charts/redirects/.helmignore
- charts/redirects/Chart.yaml
- charts/redirects/templates/ingresses.yaml
- charts/redirects/values.yaml
- k8s/helmfile/env/local/redirects.values.yaml.gotmpl
- k8s/helmfile/env/production/redirects.values.yaml.gotmpl
- k8s/helmfile/env/staging/redirects.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T365494
Some discussion around what status code to use happened on Mattermost https://mattermost.wikimedia.de/swe/pl/hdmn83gjrbbquf4911pb3k5hkc
This PR adds a chart that lets users define a list of from/to pairs that will create top level ingresses that redirect to the given URL.
Currently, the only use case is to redirect (temporarily) `status.wikibase.cloud` to `https://wmde.github.io/wikibase-cloud-status/`.
A few questions:
- Does this really need to be so complex? Is there a simpler way to do this, e.g. by configuring the `ingress-nginx/ingress-nginx` chart correctly?
- In the long run, does it even make sense to deploy this to staging?
> feat(k8s): add redirect for status page

- tf/env/production/platform-summary-dashboard-json.json
- tf/env/staging/platform-summary-dashboard-json.json
https://phabricator.wikimedia.org/T314481
I double checked this with Anton in a call. Things look correct to him.
This updates the Platform Summary Dashboards for Staging and Production to resemble the manually edited ["Copy of Platform Summary (Staging) – May 31, 2024 9:25" Dashboard](https://console.cloud.google.com/monitoring/dashboards/builder/ad392594-80d4-4fde-9de7-94b2f03144f7;duration=P31D?project=wikibase-cloud)
Did I miss anything in production that is still pointing to staging?
> chore(monitoring): update platform summary dashboard

- k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T365492
> feat(ingress-nginx): add custom error pages for 50[2,3] responses in top level ingress

- .github/pull_request_template.md
No ticket. This has been discussed in the Wikibase Cloud Team Retro on the 22nd of May and was deemed a good idea.
Team members who haven't been in the retro can check the board: https://wmde.eu.teamretro.com/meetings/1rYBtTuf0TgcfowL8lr0qq?groupId=7ec09bcd-cb5a-4c9c-8b5c-46529f0e2981
Adds a file that GitHub will automatically pick up as a template when a new PR is created. This aims to be the description of the Pull Request, not the commit message when squashing the PR into the `main` branch.
General feedback on what you as your reviewer persona, as well as someone debugging "issues from the past" would like to see provided in a Pull Request. There sure is a tradeoff to make as making this template even more detailed will create even more inertia, but at least to me, filling out these …
> repo: add proposal for pull request template

- k8s/helmfile/env/local/ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/ui.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1687
> Revert "Staging+Local: Deploy new UI image ghcr.io/wbstack/ui:sha-3157692"

- tf/env/production/variables.tf
- tf/env/staging/variables.tf
Remove tf state access for frederik.ring@wikimedia.de
Any other places where the name is hardcoded?
none
none
> chore: offboard frederik ring

- .github/workflows/check-generated-values.yml
See if yq is actually just a builtin
> gh-action: use yq as a builtin

- charts/argocd-apps/templates/wbaas-ui.yaml
- charts/argocd-config/templates/app-of-apps.yaml
- k8s/helmfile/helmfile.yaml
- staging: uninstall ui release
- staging: install argo app-of-apps
This turns pruning off to be more cautious about the possible implications of it
This is the staging follow up to #1686
https://phabricator.wikimedia.org/T360875
> staging: argocd ui deployment

- k8s/helmfile/argo-cd.yaml
This deployes ArgoCD on the production cluster
https://phabricator.wikimedia.org/T373181
> production: Deploy ArgoCD

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T373181
! needs ArgoCD on production first !
https://github.com/wmde/wbaas-deploy/pull/1754
- mark ui as uninstalled in helmfile
- deploy argocd config chart to production
> prod: manage UI via argocd

- k8s/helmfile/helmfile.yaml
`argocd-config` chart version was bumped to 1.0.2 in all environments.
Bug: T374418
> Change argocd-config version to 1.0.2 in helmfile

- k8s/argocd/local/api.values.yaml
- k8s/argocd/production/api.values.yaml
- k8s/argocd/staging/api.values.yaml
https://phabricator.wikimedia.org/T374217
command used: `./bin/generate-values production api`
> argo: add generated api value files

- k8s/helmfile/env/local/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
Update to new Queryservice Tag on staging
Just basic sanity check
Anton and @deer-wmde on mattermost
Bug: T364449
Bug: T375375
> Staging+Local: Deploy new Queryservice image 0.3.135-wbstack.5

- k8s/helmfile/cert-manager.yaml
https://phabricator.wikimedia.org/T377106
> reduce cert manager log level

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T374217
deploys api to local/staging via argocd-config v1.0.6
> local/staging: deploy api via argocd

- k8s/helmfile/env/local/tool-quickstatements.values.yaml.gotmpl
- k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl
- k8s/helmfile/env/staging/tool-quickstatements.values.yaml.gotmpl
Update the quickstatements image to use version 1.3.7 
https://phabricator.wikimedia.org/T325871
> Update Quickstatements to 1.3.7 on all environments

- skaffold/skaffold.yaml
Loosely depends on https://github.com/wbstack/mediawiki/pull/379
> chore(skaffold): enable Xdebug by default for MediaWiki

- k8s/helmfile/helmfile.yaml
deploys redis to staging via argocd-config 1.0.8
Bug: T375195
> staging: deploy redis via argocd

- k8s/helmfile/env/staging/argo-cd-base.values.yaml.gotmpl
> staging(argocd): increase memory request and limit

- k8s/argocd/production/redis.values.yaml
- k8s/argocd/staging/redis.values.yaml
- k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl
- k8s/helmfile/env/production/elasticsearch-2.values.yaml.gotmpl
- k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
- k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
- k8s/helmfile/env/production/platform-nginx.values.yaml.gotmpl
- k8s/helmfile/env/production/queryservice-gateway.values.yaml.gotmpl
- k8s/helmfile/env/production/queryservice-ui.values.yaml.gotmpl
- k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
- k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/production/redis.values.yaml.gotmpl
- k8s/helmfile/env/production/sql.values.yaml.gotmpl
- k8s/helmfile/env/production/superset.values.yaml.gotmpl
- k8s/helmfile/env/production/tool-cradle.values.yaml.gotmpl
- k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl
- k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl
- k8s/helmfile/env/staging/elasticsearch-2.values.yaml.gotmpl
- k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice-gateway.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
- k8s/helmfile/env/staging/sql.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1842
> Revert "helmfile: remove null cpu limits"

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T375195
deploys redis on production via argocd-config 1.0.9
> prod: deploy redis via argocd

- k8s/argocd/production/redis.values.yaml
- k8s/argocd/staging/redis.values.yaml
- k8s/helmfile/env/production/redis.values.yaml.gotmpl
> argo: redis remove null cpu limit

- .github/workflows/check-generated-values.yml
> gh-action: fix check-generated-values

- k8s/helmfile/env/staging/platform-nginx.nginx.conf
> Staging: Route 2 wikis to alpha mediawiki deployment

- k8s/helmfile/env/staging/platform-nginx.nginx.conf
Bug: [T378743](https://phabricator.wikimedia.org/T378743)
> Remove the || from nginx config conditions

- k8s/helmfile/env/production/private.yaml
- k8s/helmfile/env/staging/private.yaml
While looking at local TLS setup and trying to understand our certificate setup I came across some things that can be cleaned up.
- removed certificate config from private.yaml
- as this seems unused and moved to certificates.values.yaml.gotmpl in the past
- removed a confusing comment, because as far as I can tell that value is still used on the other hand
Diffs should result in *no changes* for staging or production
https://phabricator.wikimedia.org/T378691
> cleanup private.yaml (staging/prod)

- k8s/helmfile/env/staging/platform-nginx.nginx.conf
> enable wikibasequalitycontraint on wbqc-2-alpha.wikibase.dev

- k8s/argocd/local/app-of-apps.values.yaml
- k8s/argocd/production/app-of-apps.values.yaml
- k8s/argocd/staging/app-of-apps.values.yaml
- k8s/helmfile/env/production/argocd-config.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
> [!IMPORTANT]
> needs https://github.com/wbstack/charts/pull/173
https://phabricator.wikimedia.org/T377585
deploys/uses https://github.com/wbstack/charts/pull/173 in local & staging 
- **add chart versions for argocd**
- **add app-of-apps chart version**
> local/staging: use argocd-config 1.1.0

- k8s/argocd/local/app-of-apps.values.yaml
- k8s/argocd/production/app-of-apps.values.yaml
- k8s/argocd/staging/app-of-apps.values.yaml
- k8s/helmfile/env/production/argocd-config.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
Reverts wmde/wbaas-deploy#1908
for some reason the change for the UI deployment did not work
> Revert "local/staging: use argocd-config 1.1.0"

- k8s/helmfile/env/production/argocd-config.values.yaml.gotmpl
- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T377585
https://github.com/wmde/wbaas-deploy/pull/1885/files
uses argocd-config chart v0.1.0 on production
> prod: use argocd-config 1.1.0

- tf/env/staging/providers.tf
> Update google tf provider from 6.5.0 to 6.17.0

- tf/env/production/providers.tf
> Prod: Update google tf provider from 6.5.0 to 6.17.0

- k8s/helmfile/env/local/tool-widar.values.yaml.gotmpl
- k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl
https://phabricator.wikimedia.org/T383866
> local/staging: use widar image sha-c5890d8

- k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl
https://phabricator.wikimedia.org/T383866
> prod: widar sha-c5890d8

- k8s/helmfile/env/local/tool-cradle.values.yaml.gotmpl
- k8s/helmfile/env/staging/tool-cradle.values.yaml.gotmpl
https://phabricator.wikimedia.org/T383873
> local/staging: use cradle sha-90c5836

- k8s/helmfile/env/production/tool-cradle.values.yaml.gotmpl
https://phabricator.wikimedia.org/T383866
> prod: use cradle sha-90c5836

- tf/env/production/variables.tf
- tf/env/staging/variables.tf
Username change needs to be reflected in terraform
> hr: rename shotton to hyde

- doc/dumping-wikis.md
Some documentation on how to create XML/JSON dumps for user wikis in light of https://phabricator.wikimedia.org/T385154
> docs: add dumping-wikis.md

- tf/env/staging/monitoring.tf
This resource was existing already on google cloud.
This imports the state into terraform and also uses it as a test bed to try a more precise extractor for the labels.
Bug: T385969
> staging(tofu): import staging-site-request-count

- tf/env/staging/dns-local.tf
This adds DNS records for wbaas.dev, pointing it and all subdomains to 127.0.0.1
I added this in the staging env because locally we do no have the GCP provider configured and I am not sure if it's worth it for this. Thoughts?
Bug: https://phabricator.wikimedia.org/T383335
> tf: add wbaas.dev DNS

- bin/local/README.md
- bin/local/create-local-wiki.sh
- doc/deployments/argocd.md
- doc/local-dev-env.md
- doc/minikube-load-balancer.md
- k8s/argocd/local/api.values.yaml
- k8s/argocd/local/ui.values.yaml
- k8s/helmfile/env/local/adminer-cetic.values.yaml.gotmpl
- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/local/argo-cd-base.values.yaml.gotmpl
- k8s/helmfile/env/local/base.yaml
- k8s/helmfile/env/local/certificates.values.yaml.gotmpl
- k8s/helmfile/env/local/kube-prometheus-stack.values.yaml.gotmpl
- k8s/helmfile/env/local/mailhog.values.yaml.gotmpl
- k8s/helmfile/env/local/minio.values.yaml.gotmpl
- k8s/helmfile/env/local/private.yaml
- k8s/helmfile/env/local/redirects.values.yaml.gotmpl
- tf/env/local/config-map.tf
https://phabricator.wikimedia.org/T383335#10591561
- mostly just replaces occurences of `wbaas.localhost` with `wbaas.dev`
- updates some documentation
> replace `wbaas.localhost` with `wbaas.dev`

- tf/env/staging/dns-local.tf
For me from time to time my system has trouble resolving wbaas.dev - maybe increased TTL will help? Did anyone else experience this?
> increase wbaas.dev DNS TTL

- k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T390071
> use wbstack/redirects 2.0.0

- tf/env/production/cluster.tf
Reverts wmde/wbaas-deploy#2055
Error during apply `Error: error creating NodePool: googleapi: Error 404: Not found: projects/wikibase-cloud/locations/europe-west3/clusters/wbaas-3`
> Revert "prod(tf): add node pool without highthroughput logging"

- k8s/helmfile/env/staging/argo-cd-base.values.yaml.gotmpl
reduction of argou resource requests on staging
> staging: reduce argo resource requests

- tf/env/staging/.terraform.lock.hcl
> staging(tf):bump lock for google provider

- tf/env/production/.terraform.lock.hcl
- tf/env/production/providers.tf
also update lockfile
Bug: T391569
> prod(tf): bump google tf provider to 6.29.0

- tf/env/production/cluster.tf
Follow up to remove this old node pool that still has high throughput logging enabled
Bug: T390698
> prod(tf): remove old node pool

- tf/env/production/cluster.tf
Follow up to remove n2 node pool
Bug: T390698
> prod(tf): remove old n2 node pool

- tf/env/production/cluster.tf
After trying to move to n4-highmem-8 went sideways let's still try to downsize this cluster as a quick win to save some resources
follow-up to remove old n2-highmem-16
Bug: T390698
> prod(tf): add n2-highmen-8 node pool

- tf/env/production/cluster.tf
> prod(tf): remove old n2-highmem-16

- k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
Values determined by looking at last 2 weeks resource utilisation data and using the new GKE recommended request metric
Bug: T390698
> prod(k8s): reduce queryservice cpu requests

- k8s/argocd/local/api.values.yaml
- k8s/argocd/staging/api.values.yaml
- k8s/helmfile/env/local/api.values.yaml.gotmpl
- k8s/helmfile/env/staging/api.values.yaml.gotmpl
somehow the auto PR creation did not happen for https://github.com/wbstack/api/pull/924
> staging/local: use api image 10x.19.0

- doc/local-dev-env.md
Add some very short docs about debugging sql db in minikube
> docs: local-dev-env add sql docs

- doc/deployments/deploying-updated-code.md
include short caveat for components that now have auto-generated deploy PRs
> doc: deploying-updated-code.md

- k8s/helmfile/tailscale-operator.yaml
> chore(staging): update tailscale operator to 1.84.2

- k8s/helmfile/tailscale-operator.yaml
> chore(prod): update tailscale operator to 1.84.2

- k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
New image includes correctly setting useragent env variable
Bug: T397052
> Production: Deploy new Queryservice image 0.3.135-wbstack.7

- k8s/helmfile/env/local/queryservice-ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice-ui.values.yaml.gotmpl
> local+staging(k8s): update queryservice-ui to 1.8

- k8s/helmfile/env/production/queryservice-ui.values.yaml.gotmpl
> production(k8s): update queryservice-ui to 1.8

- k8s/helmfile/env/local/queryservice-ui.values.yaml.gotmpl
- k8s/helmfile/env/staging/queryservice-ui.values.yaml.gotmpl
> local+staging(k8s): update queryservice-ui to 1.9

- k8s/helmfile/env/production/queryservice-ui.values.yaml.gotmpl
> production(k8s): update queryservice-ui to 1.9

- doc/README.md
- doc/handling-high-traffic.md
> docs: Handling High Traffic
