wmde/wbaas-deploy

bin/get-unused-invite-codes
I wrote a little bash script to get all current unused invite codes of the production wikibase.cloud instance. There is a doc (which link is getting echo'd as well) which tracks them and needs to be updated from time to time. Hope this helps. 
The script switches to the right cluster context if needed and switches back to the old context if another one was active to avoid work disruption
=> Add bash script for getting unused invite codes

k8s/helmfile/helmfile.yaml
`platform-apps-ingress` in `local` and `staging` use `charts/wikibase-ingress` in `charts` repo. `production` one uses the chart in `wbaas-deploy` still.
=> Use charts/wikibase-ingress in local and staging

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
This is the production counterpart to https://github.com/wmde/wbaas-deploy/pull/590
`nginx-ingress` chart usage gets removed from helmfile by this
=> k8s: prod migrate to ingress-nginx

Makefile
As we are upgrading our GKE clusters to use `1.22.15-gke.1000` we also will use k8s version 1.22.15 with minikube from now on
=> local: use k8s 1.22.15

k8s/helmfile/helmfile.yaml
Removes the now unused `ingress-nginx` configuration.
Note: should only be merged if devs are aware of it in regards to their local cluster
=> cleanup helmfile.yaml

tf/env/production/monitoring.tf
It turns out that that container name is now just
"controller" let's target this by label instead.
=> tf: fix filter for ingress-nginx logging metric

k8s/helmfile/helmfile.yaml
This PR fixes setting up the cluster locally from scratch, see https://phabricator.wikimedia.org/T322542#8417755
=> local: use adminer chart v0.2.1 for GA ingress handling

tf/modules/CHANGELOG.md, tf/modules/buckets/main.tf
https://phabricator.wikimedia.org/T321091
This re-adds the [retention policy](https://cloud.google.com/storage/docs/bucket-lock) to the backup bucket. 
Note: Apperantly this caused an issue with writing files to the bucket some time ago? https://github.com/wmde/wbaas-deploy/commit/fef908d315fd1ba87d9a8d2c7e1cbe2703db8ec3 
Let's use this for staging only and see if it works.
=> tf-module-buckets-1: backup bucket retention policy

tf/modules/buckets/main.tf
A fix for the faulty `tf-module-buckets-1`: https://github.com/wmde/wbaas-deploy/pull/608
We wanted to keep the retention policy unlocked for testing this out.
=> tf-module-buckets-2: fix temporarily retention policy

k8s/helmfile/env/local/mailhog.values.yaml
Since changing to ingress-nginx this is now needed in order for the controller to handle this ingress
=> k8s: add ingress.class annotation to mailhog Ingress

k8s/helmfile/env/production/ui.values.yaml.gotmpl
Bump follow-redirects from 1.13.2 to 1.15.2
Bump express from 4.17.1 to 4.18.2
Bug: T325345 Bug: T325350
=> prod: Bump follow-redirects and express

tf/modules/buckets/main.tf
Removes the backup bucket retention policy again, because we can't use it yet, see https://phabricator.wikimedia.org/T321091#8470662
=> tf-module-buckets: remove retention policy again

k8s/helmfile/env/production/private.yaml
Reverts wmde/wbaas-deploy#636
```
Error: UPGRADE FAILED: cannot patch "sql-mariadb-primary" with kind StatefulSet: StatefulSet.apps "sql-mariadb-primary" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden && cannot patch "sql-mariadb-secondary" with kind StatefulSet: StatefulSet.apps "sql-mariadb-secondary" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
make: *** [Makefile:87: apply-production] Error 1
```
=> Revert "k8s: prod: increase sql storage size to 120GB"

.github/workflows/mattermost.yml
When processing a PR title containing double quotes we construct invalid JSON as these double quotes are never escaped. Instead, escape the title using `jq`.
E.g.: https://github.com/wmde/wbaas-deploy/pull/638
=> fix: "double quotes" break json payload being sent to mattermost hook

k8s/helmfile/env/common/redis.values.yaml.gotmpl, k8s/helmfile/env/local/redis.values.yaml.gotmpl, k8s/helmfile/env/production/redis.values.yaml.gotmpl, k8s/helmfile/env/staging/redis.values.yaml.gotmpl
This PR removes the duplicated configuration of redis and uses the same common config for all environments.
=> refactor(helm): redis values are repeated across envs

k8s/helmfile/env/common/tool-cradle.values.yaml.gotmpl, k8s/helmfile/env/common/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/common/tool-widar.values.yaml.gotmpl, k8s/helmfile/env/local/tool-cradle.values.yaml.gotmpl, k8s/helmfile/env/local/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/local/tool-widar.values.yaml.gotmpl, k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-cradle.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl
This PR removes the duplicated configuration of tool-cradle|widar|quickstatements and uses the same common config for all environments.
=> refactor(helm): tool-cradle|widar|quickstatements values are repeated across envs

k8s/helmfile/env/common/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/common/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/common/queryservice.values.yaml.gotmpl, k8s/helmfile/env/local/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/local/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/local/queryservice.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
This PR removes the duplicated configuration of queryservice-ui|gateway|update and uses the same common config for all environments.
This state diffs cleanly against staging and production.
For local this would contain the following change:
```diff
...
app.kubernetes.io/instance: queryservice-updater
spec:
containers:
- name: queryservice-updater
image: "ghcr.io/wbstack/queryservice-updater:0.3.84_3.9"
-           imagePullPolicy: IfNotPresent
+           imagePullPolicy: Always
env:
- name: WBSTACK_LOOP_LIMIT
value: "100"
- name: EXTRA_JVM_OPTS
...
```
which I currently assume is an unwanted inconsistency. If this is not correct, we can obviously change it back.
=> refactor(helm): queryservice-ui|gateway|updater values are repeated across envs

k8s/helmfile/env/common/api.values.yaml.gotmpl, k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
This PR removes the duplicated configuration of api and uses the same common config for all environments.
=> refactor(helm): api values are repeated across envs

k8s/helmfile/env/common/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/local/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/production/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
This PR removes the duplicated configuration of elasticsearch and uses the same common config for all environments.
=> refactor(helm): elasticsearch values are repeated across envs

k8s/helmfile/env/common/mediawiki-137-fp.values.yaml.gotmpl, k8s/helmfile/env/local/mediawiki-137-fp.values.yaml.gotmpl, k8s/helmfile/env/production/mediawiki-137-fp.values.yaml.gotmpl, k8s/helmfile/env/staging/mediawiki-137-fp.values.yaml.gotmpl
This PR removes the duplicated configuration of mediawiki and uses the same common config for all environments.
This state diffs cleanly against staging and production.
For local this would contain the following change:
```diff
default, mediawiki-137-fp-app-alpha, Deployment (apps) has changed:
...
- name: MW_ELASTICSEARCH_PORT
value: "9200"
- name: MW_MAILGUN_DISABLED
value: "yes"
- name: MW_MAILGUN_API_KEY
-             value: "this is a a fake api key"
+             value: "1.234567e+06"
- name: MW_MAILGUN_DOMAIN
value: examplemaildomain.localhost
- name: MW_MAILGUN_ENDPOINT
-             value: https://api.mailgun.net
+             value: https://some.api.endpoint.example
- name: MW_EMAIL_DOMAIN
value: …
```
=> refactor(helm): mediawiki values are repeated across envs

k8s/helmfile/env/common/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/local/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/staging/wbaas-backup.values.yaml.gotmpl
This PR removes the duplicated configuration of wbaas-backup and uses the same common config for all environments.
=> refactor(helm): wbaas-backup values are repeated across envs

k8s/helmfile/helmfile.yaml
Just a small cleanup PR, I thought this might make sense, because mailhog and adminer will never-ever get deployed somewhere else than `local` and also this gets rid of the `skipping missing values file matching "env/common/..."` lines for these releases while using the Makefile.
=> cleanup helmfile: remove yaml template for local-only deployments

k8s/helmfile/env/common/sql.values.yaml.gotmpl, k8s/helmfile/env/local/sql.values.yaml.gotmpl, k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
This PR removes the duplicated configuration of api and uses the same common config for all environments.
This state diffs cleanly against local and staging. In production, a missing command is added to the db's init script:
```diff
default, sql-mariadb-primary-init-scripts, ConfigMap (v1) has changed:                                                                                                                                     
...                                                                                                                                                                                                        
helm.sh/chart: mariadb-10.5.0 …
```
=> refactor(helm): sql values are repeated across envs

Makefile
This is an attempt at cleaning up the Makefile which mostly aims at me better understanding what the targets do.
Things that have been changed:
- A mechanism for displaying help is added. This means that `make` or `make help` will blurt out some text like this:
```
TARGETS:
help                  Print this message
minikube-start        Start a local k8s cluster using minikube
minikube-stop         Stop the local minikube cluster
minikube-delete       Delete the local minikube cluster
minikube-pause        Pause the local minikube cluster
minikube-unpause      Unpause the local minikube cluster
minikube-dashboard    Open the Kubernetes Dashboard for your local cluster in your browser
minikube-tunnel       Open a tunnel to the local cluster and expose it on an IP on the host system …
```
=> refactor(makefile): use same commands for envs and modules, add help

k8s/helmfile/env/local/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
I noticed that applying the current state to my local cluster makes ES fail to run as the affinity rules won't work for the minikube cluster:
```
Events:
Type     Reason            Age                 From               Message
----     ------            ----                ----               -------
Warning  FailedScheduling  118s                default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.
Warning  FailedScheduling  34s (x1 over 103s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.
```
This PR makes local env use `soft` affinity instead.
=> fix(local): elasticsearch pods need to run on the same node locally

k8s/jobs/runAllMWJobs.sh
Running `WBS_DOMAIN=foo.wbaas.localhost ./loadElasticsearchAndRunMWJobs.sh` currently prints an error about a file that is never referenced and/or created anywhere else:
```
jq: error: Could not open file queryservice_pod.json: No such file or directory
```
=> fix(jobs): mw jobs script references inexistent json file

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
#722 did not work at all
```
Defaulted container "elasticsearch" out of: elasticsearch, configure-sysctl (init)
Exception in thread "main" org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger transport
at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createLogger(PropertiesConfigurationBuilder.java:256)
at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:178)
at org.elasticsearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:214)
at org.elasticsearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:182)
at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFa …
```
=> chore(es-staging): revert non-working logging changes

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
It seems there is no official way to set the log levels globally. so we need to this for all packages: https://www.elastic.co/de/blog/elasticsearch-logging-secrets
The list of packages is taken from a cloned `elasticsearch` repo. Logs a lot of things in the "boot" phase when run locally, might be insightful to see this in staging.
=> chore(es-staging): explicitly set all loggers to DEBUG level

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Inspecting the logs with DEBUG level show that the current boot process hangs in this method https://github.com/elastic/elasticsearch/blob/eef62fe2b992cd7f8defb9bfeaf2b9a399a37540/server/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java#L108-L146
Let's see what happens if we allow for more memory to be consumed by this operation.
---
I tried this locally where it seemed to have some positive impact.
=> chore(es-staging): try increasing memory allowed for indexing

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T329551
> :warning: depends on https://github.com/wbstack/charts/pull/111
This PR uses api chart v0.20.2, which introduces the option to set the `WBSTACK_ELASTICSEARCH_ENABLED_BY_DEFAULT` env var via the charts values.
The option gets enabled for local and staging, but not production (although the new chart is used everywhere)
=> (local/staging) enable ES for new wikis

k8s/helmfile/env/production/api.values.yaml.gotmpl
https://phabricator.wikimedia.org/T329551
> :warning: depends on https://github.com/wmde/wbaas-deploy/pull/735
Enables ES for new wikis on production
=> (prod) Enable ES for new wikis

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl
The default scraping of all k8s components is currently creating ~500 samples per second noone of us will ever have a look at (or not yet). For now, we can disable these and try to get the metrics we are interested in first.
=> chore(monitoring): stop scraping k8s components

k8s/helmfile/env/local/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/staging/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
It seems #742 set up collection correctly, so we can try exporting ES metrics next.
=> feat(monitoring): deploy elasticsearch exporter to staging

k8s/helmfile/env/local/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/staging/ingress-nginx.values.yaml.gotmpl
The `ingress-nginx` controller lets us create a ServiceMonitor object for it, so we can try enabling it and see if there is helpful data to be returned.
=> feat(monitoring): add service monitor for ingress-nginx controller in local and staging

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
#744 implicitly put the `ServiceMonitor` into the `kube-system` namespace while all other monitors are in `monitoring`.
=> fix(monitoring): ingress-nginx servicemonitor should be located in monitoring namespace

k8s/helmfile/env/local/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/staging/ingress-nginx.values.yaml.gotmpl
Production equivalent of #744 
Depends on #749
=> feat(monitoring): enable ingress-nginx metrics in production

k8s/helmfile/env/local/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/staging/prometheus-elasticsearch-exporter.values.yaml.gotmpl
Looking at the recently introduced ES metrics in GCP, it occured to me there is no way to distinguish the data coming from staging and production environments. This seems to be due to the fact that GKE would like to use a  `cluster` label for providing that information (it does so for the nginx metrics), but fails to do so for ES as the ES exporter already uses this label to provide the ES cluster's name.
This PR tries to fix the situation by relabeling the `cluster` value that is provided to `es_cluster`.
This is tested locally where it worked for me. The PR also contains the changes for staging.
=> fix(staging): es exporter label collides with gke provided ones

k8s/helmfile/env/local/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/staging/prometheus-elasticsearch-exporter.values.yaml.gotmpl
#752 seems to have worked in staging, so let's also try production
=> fix(prod-monitoring): cluster label is overloaded for es metrics and needs renaming

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl
We see a lot of exporter errors like this in production right now:
```
level=warn ts=2023-02-23T14:20:43.086498137Z caller=indices_settings.go:167 msg="failed to fetch and decode cluster settings stats" err="failed to get from http://elasticsearch-master.default.svc.cluster.local:9200/_all/_settings: Get \"http://elasticsearch-master.default.svc.cluster.local:9200/_all/_settings\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2023-02-23T14:20:53.087469215Z caller=indices_settings.go:167 msg="failed to fetch and decode cluster settings stats" err="failed to get from http://elasticsearch-master.default.svc.cluster.local:9200/_all/_settings: Get \"http://elasticsearch-master.default.svc.cluster.local:9200/_all/_settings\": context deadline …
```
=> chore(monitoring): raise es and prometheus scrape timeout

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl
Applying #754 works just fine, however the created `Prometheus` resource will have a sneaky message in its metadata about how it cannot use the given configuration:
```
Message:               creating config failed: generating config failed: scrapeTimeout "60s" greater than scrapeInterval "30s"
```
This PR lowers the timeout a bit, while raising the interval, so that the change will actually take effect. Also, these limits are now also adjusted for ES. Everything else can still be monitored at the default intervals.
=> fix(monitoring): scrape timeout cannot be greater than scrape interval

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl
The Prometheus Operator as well as the ElasticSearch exporter currently run with no resource limits set. We should limit them from guarding against unwanted runaway resource usage.
=> fix(monitoring): set resource limits for unbounded pods

k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl
Since #759, the ElasticSearch exporter is stuck in CrashLoopBackoff. While the logs do not show anything suspicious, I assume this is caused by resource limits.
=> fix(monitoring): es exporter crashes when running with limited resources

k8s/helmfile/env/local/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl, k8s/helmfile/env/staging/prometheus-elasticsearch-exporter.values.yaml.gotmpl
The pod is still crashing, even with the limits from #761
=> fix(monitoring): further raise memory limits for es exporter

k8s/helmfile/env/local/kube-prometheus-stack.values.yaml.gotmpl
Sometimes, I still have the prometheus-operator failing to create the prometheus pods in local development. There is no real indication as of why, but lowering resource limits seems to help getting it up and running consistently.
=> chore(local): prometheus defaults exceed available resources

.github/workflows/test.yaml
Running the `test` action in this repository currently results in a warning:
Instead of changing the default node version in the v2 checkout action, we can also just upgrade to v3.
=> chore(ci): checkout v2 uses deprecated node version

k8s/jobs/loadElasticSearchOnly.sh, k8s/jobs/rebuildQuantityUnitsJob.sh, k8s/jobs/runAllMWJobs.sh
I keep checking these in to source control, and this might be the cheapest way to keep me from doing so.
=> chore(jobs): use one-off temp files for storing pod spec

k8s/helmfile/env/production/prometheus-elasticsearch-exporter.values.yaml.gotmpl
After having a look at how this behaves in production (without crashing), it seems the RAM consumed is always slightly below 1GB, meaning we can lower the allocation a bit again.
=> chore(monitoring): lower es exporter limits

k8s/helmfile/helmfile.yaml
Ticket: https://phabricator.wikimedia.org/T331270
Before actually removing code and configuration, we'll need to "uninstall" the release.
=> chore(monitoring): stats-cron has been superseded

k8s/helmfile/env/production/ui.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
Requires #779 and https://github.com/wbstack/charts/pull/112
UI can serve as a better canary than ElasticSearch itself, allowing us to roll back changes more easily in case something unexpected goes wrong.
=> feat(monitoring): collect service metrics for ui

Makefile, doc/local-dev-env.md
Adds `helmfile-sync` make target and some documentation.
Sometimes an initial `make apply-local` times out (or something) and helm seems to be confused on what is actually deployed and what is not. An usual symptom of this is that the API pods aren't deployed.
=> (makefile) Add `helmfile-sync`

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
Ticket: https://phabricator.wikimedia.org/T328740
It seems the `fetch_shard_store` thread pools max out their limit (currently 20 in production) when a sibling node is currently booting / recovering. Let's see if raising this limit can help us make the startup procedure a bit faster.
=> chore(elasticsearch): try raising limit for fetch_shard_store threadpool in staging

k8s/helmfile/env/staging/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl
Quickstatements is currently broken in staging as authentication still expects the (already removed) 1.37 deployment to present.
=> fix(mediawiki): point oauth consumers to correct mediawiki host

k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl
**only deploy this after each wiki was upgraded** otherwise we would need second instances of these service deployments I think.
This rewires our OAuth services QuickStatements & Widar to talk with the mw 1.38 deployment
=> Rewire OAuth services QuickStatements & Widar to talk with the mw 1.38 deployment

k8s/helmfile/helmfile.yaml
To be done once the production migration to 1.38 is finished.
=> chore(mediawiki): uninstall mediawiki 1.37 release

k8s/helmfile/helmfile.yaml
=> Remove 1.37 MediaWiki release

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/local/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/local/platform-nginx.nginx.conf, k8s/helmfile/env/local/platform-nginx.values.yaml.gotmpl, k8s/helmfile/env/local/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/local/tool-widar.values.yaml.gotmpl, k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/staging/tool-widar.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
For staging and local, this PR:
- adds a 1.39 MediaWiki release in parallel to 1.38
- updates api to use 1.39 schemas for newly created wikis
- points OAuth consumers to the 1.39 release
In staging only:
- map all existing wikis to 1.38 for now, so that they can be migrated in a later step
=> feat(mediawiki): deploy 1.39 release to local and staging and use for newly created wikis

k8s/helmfile/env/production/elasticsearch.values.yaml.gotmpl
In order to test the hypothesis that istio
is causing some errors in pinging between pods
lets try removing it in production and staging
=> k8s: remove istio from elasticsearch

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
This should allow us to find out whether Istio / Envoy do indeed interfere with intra-ES-cluster traffic or if this is a red herring.
Ideally, after deploying, no messages like this would be logged anymore:
```
[2023-03-27T16:52:50,521][WARN ][o.e.d.z.ZenDiscovery     ] [elasticsearch-master-2] master left (reason = failed to ping, tried [3] times, each with  maximum [30s] timeout), current nodes: nodes: 
```
=> chore(elasticsearch): in staging, enable istio while excluding cluster transport from being proxied

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
This was missed in #824 
See: https://istio.io/latest/docs/reference/config/annotations/
=> fix(elasticsearch): port exclusion rules need to be given in annotation

k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl
#830 seems to have broken networking entirely as nodes using that configuration are stuck in a loop of:
```
[2023-04-03T08:59:57,784][INFO ][o.e.d.z.ZenDiscovery     ] [elasticsearch-master-2] failed to send join request to master [{elasticsearch-master-1}{VtC1F-NsQvGqWaeuOXj9WA}{aqmhXCrqRqyPcLWmv6tltg}{10.112.0.30}{10.112.0.30:9300}{xpack.installed=true}], reason [RemoteTransportException[[elasticsearch-master-1][10.112.0.30:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[elasticsearch-master-2][10.112.1.40:9300] general node connection failure]; nested: TransportException[handshake failed because connection reset]; ]
```
It's not entirely clear how the precendence of the options in https://istio.io/latest/docs/reference/config/annotations/ works, but trying to …
=> fix(elasticsearch): try "include" annotation rule for inbound es traffic

charts/istio-service-mesh/templates/peer-authentication.yaml, charts/istio-service-mesh/values.yaml, k8s/helmfile/env/local/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/local/istio-service-mesh.values.yaml.gotmpl, k8s/helmfile/env/staging/elasticsearch.values.yaml.gotmpl, k8s/helmfile/env/staging/istio-service-mesh.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T333807
The default value of `PERMISSIVE` should work as per documentation (as it allows for both encrypted as well as unencrypted traffic), however this is not what we are seeing in staging. Instead, we can try hard disabling mTLS and see if it makes a difference.
=> Hard disable Istio mTLS in staging

tf/modules/CHANGELOG.md, tf/modules/uptime/main.tf, tf/modules/uptime/variables.tf
Add uptime check and alert to uptime module for a
mediawiki api endpoint that depends on being able to contact elasticsearch.
This endpoint was chosen because it appears to always contact elasticsearch in order to obtain the mapping.
In order to determine success or failure we have to inspect the actual JSON response from the api since even errors return an HTTP status 200.
Doing this has resulted in exposing more of the underlying resources to the local configuration and added to the complexity of reading the resource and the module variables. However, it does ensure consistency with our other uptime checks and alerts.
This commit doesn't see this module actually being used
=> tf: uptime for CirrusSearch backed MediaWiki api

Makefile, skaffold/skaffold.yaml
The local skaffold conf still uses mw 1.38 even though we already use 1.39 locally as the main mw release.
Also I renamed the Makefile target so that it is obvious which mw version is gonna get deployed (I got bitten by this several times now :P)
=> local: update skaffold mw conf to 1.39

k8s/helmfile/env/production/platform-nginx.nginx.conf
This patch hopes to test if we see the issues described in T334912 go away by reverting to this wiki using 1.38 mediawiki
=> k8s: beyond-notability.wikibase.cloud to 1.38

k8s/helmfile/env/production/platform-nginx.nginx.conf
Reverts wmde/wbaas-deploy#851
Take wiki to 1.39 workloads in preparation for running `update.php`
=> Revert "k8s: beyond-notability.wikibase.cloud to 1.38"

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T333559
Changes in `api`: https://github.com/wbstack/api/compare/8x.11.0...8x.11.1
=> chore(k8s): update api image version to 8x.11.1 in staging and local

k8s/helmfile/env/production/api.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T333559
Changes in `api`: https://github.com/wbstack/api/compare/8x.11.0...8x.11.1
=> chore(k8s): update api image version to 8x.11.1 in production

tf/env/production/metric-alarms.tf, tf/env/staging/metric-alarms.tf
This was missed in #877 which means current `main` would create the same alarm twice.
=> fix(tf): remove duplicate alarm definitions

tf/modules/monitoring/metric-alarms.tf
Currently, an alarm for ES health is raised when there has been a period of 2 minutes without any data. It seems this is relatively common in production and data just takes a while to arrive there.
Most alarms that are triggered right now last around 30 seconds, so raising this to 5 minutes should be a very conservative option for silencing these false positives.
=> chore(monitoring): wait for 5 minutes of metric absence before triggering alarm

skaffold/README.md, skaffold/skaffold.yaml
Referencing the inexistent 1.38 release somehow had my local skaffold setup end up in an infinite loop of comparing configuration files.
This PR removes the release info for 1.38, after which my local setup started working as expected again.
=> fix(skaffold): remove references to deleted 1.38 mediawiki release

k8s/helmfile/env/production/sql.values.yaml.gotmpl
Test if the site correctly falls back to being fully functional just using the master if there is no sql secondary to connect to.
=> k8s: reduce secondary sql replica count to 0

k8s/helmfile/env/staging/sql.values.yaml.gotmpl
In order to practice restoring some data on the secondary let's scale up the replica count so we have something to restore to
=> k8s staging: secondary sql replica count to 1

k8s/helmfile/env/production/sql.values.yaml.gotmpl
Lets bring this up and try to restore data into it
=> k8s: increase secondary sql replica count to 1

k8s/helmfile/cert-manager.yaml, k8s/helmfile/helmfile.yaml
Since upgrading Helmfile to `0.153.1` I was seeing this warning on every interaction:
```
Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part                                                                  
Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part                                                                  
Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part                                                                  
Warning: environments and releases cannot be defined within the same YAML part. Use --- to …
```
=> fix(helmfile): environments and releases cannot be defined within the same YAML part

k8s/helmfile/helmfile.yaml
Uses wbaas-backup v0.0.6 which introduces more verbosity settings and a table overwrite flag for restoring
=> use wbaas-backup chart v0.0.6

k8s/helmfile/env/production/sql.values.yaml.gotmpl
Temporary fix to keep the secondary from responding with stale data.
=> chore(sql): set production replica count to 0

k8s/helmfile/env/production/sql.values.yaml.gotmpl
We'll need this when choosing our next attempts on fixing the incident.
=> chore(sql): reenable production replica

k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
This will allow us to work on the secondary without affecting anything else.
=> chore(k8s): replace sql secondary references with primary ones

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
Effectively disabling the secondary SQL node for production MediaWiki pods.
=> chore(mw): bump production image

k8s/helmfile/env/production/api.values.yaml.gotmpl
After manual intervention, the secondary is ready to use again.
=> chore(api): start reading from replica again

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
After manual intervention, the secondary is ready to use again.
=> chore(mediawiki): start reading from replica again

bin/local/nuke-local.sh
I noticed that the script can fail if helmfile deps needs to run, so I added it.
=> fix nuke-local.sh: add helmfile deps

k8s/helmfile/env/local/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/staging/wbaas-backup.values.yaml.gotmpl
Makes https://github.com/wmde/wbaas-backup/pull/22 available
=> chore(backup): bump version to 0.2.0, including --overwrite-tables flag

tf/modules/k8s-secrets/main.tf
Fixup for a typo I made in #892 
I will delete the old tag so we don't spam versions.
=> fix(tf): resource names for sql secrets use plural

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml, tf/env/local/namespaces.tf, tf/env/local/secrets-api.tf, tf/env/local/secrets-recapcha.tf, tf/env/local/secrets-redis.tf, tf/env/local/secrets-sql.tf, tf/env/staging/kubernetes-secrets.tf, tf/env/staging/namespaces.tf
Requires: https://github.com/wmde/wbaas-deploy/pull/892
Ticket: https://phabricator.wikimedia.org/T330389
As discussed, we want to create a dedicated namespace that contains the rather noisy job objects. As there seems to be no official way of sharing secrets across namespaces, I went for defining the namespace in terraform and also duplicating the secrets across namespaces.
~~Leaving this a draft as it contains dev junk still.~~
=> feat(k8s): add namespace for api jobs and add secrets to both namespaces

k8s/helmfile/helmfile.yaml
This will move us to using our forked ES6 chart
which is compatible with kubernetes 1.25+
This also stops helmfile tracking our ES7 release
on staging. After merging this the ES7 release
will need to manually be cleaned up with helm
Bug: T338298
=> k8s: Use forked ES6 chart and remove ES7

tf/modules/CHANGELOG.md, tf/modules/k8s-secrets/main.tf
Ticket https://phabricator.wikimedia.org/T330389
MediaWiki jobs in the `api-jobs` namespace currently fail to start up as they fail to find a specified secret:
```
secret "smtp-credentials" not found
```
=> fix(tf): smtp credentials are missing from additional namespaces

tf/env/staging/kubernetes-secrets.tf
Applies the changes from #939 to staging
Planning against staging now outputs
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:                                                                 
+ create                                                                                                                                                                                                 
Terraform will perform the following actions:                                                                                                                                                              
+ resource "kubernetes_secret" "smtp-credentials" { …
```
=> chore(tf): bump secrets module for staging

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl
When trying to monitor the deployment of #942 I noticed we currently disable collection of all Kubernetes metrics. Enabling `kube-state-metrics` will give us metrics like job count et al: https://github.com/kubernetes/kube-state-metrics/blob/31d6e8fc265b1dadf543f2ed7da27a046c50c29f/docs/README.md
=> feat(monitoring): enable kube-state-metrics collection

k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl
Starting with #946 we exhaust node resources and the MediaWiki replicas cannot be scheduled anymore. This PR lowers the requests for all MediaWiki pods, leaving the existing limits in place.
=> chore(mw): lower resource requests for staging

tf/modules/CHANGELOG.md, tf/modules/monitoring/queryservice-pv.tf
The cross_series_reducer was wrongly set to be a sum function which resulted in the unwanted sideffect of the metric doubling for windows where two series were present.
This happens, for example, when a pod changes.
Bug: T339101
=> tf monitoring module: fix QueryService PV alerting

tf/env/staging/monitoring.tf
https://phabricator.wikimedia.org/T339101
uses `tf-module-monitoring-18` on staging, fixing erronenous Query Service PV utilization alerts https://github.com/wmde/wbaas-deploy/pull/950
=> staging: Use `tf-module-monitoring-18`

tf/env/production/monitoring.tf
https://phabricator.wikimedia.org/T339101
uses `tf-module-monitoring-18` on production, fixing erronenous Query Service PV utilization alerts https://github.com/wmde/wbaas-deploy/pull/950
=> production: Use `tf-module-monitoring-18`

k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
This is increasing the disk size in staging so I can test the procedure for getting https://github.com/wmde/wbaas-deploy/pull/968 to production safely.
=> chore(queryservice): bump disk size in staging

k8s/helmfile/env/production/queryservice.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T340525
The actual disk usage has reached the threshold of 85% today, so we need to scale it up.
=> chore(queryservice): bump disk size in production

bin/minikube-tunnel
Unfortunately I can't exactly pin down under which circumstances this can happen, but in the past it happened several times for me that the minikube-tunnel script remained hanging and I couldn't ctrl+c out of it.
Recently I stumbled over a [submission on HN](https://news.ycombinator.com/item?id=36400465) about using bash exit traps, and I wondered if this change would help with the above problem.
An alternative approach could be using `EXIT INT ABRT KILL TERM`
Overall this is just a minor convenience improvement. Did anyone else notice this problem as well at all?
=> local: improve minikube-tunnel script

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml, tf/env/production/monitoring.tf, tf/env/production/platform-summary-dashboard.tf, tf/env/staging/monitoring.tf, tf/env/staging/platform-summary-dashboard.tf
Ticket https://phabricator.wikimedia.org/T335961
Requires https://github.com/wbstack/api/pull/617 and https://github.com/wbstack/charts/pull/119
=> feat(platform-summary): add signup rate metrics

tf/env/production/platform-summary-dashboard.tf, tf/env/staging/platform-summary-dashboard.tf
Ticket: https://phabricator.wikimedia.org/T335961
Fixup for #970
---
Right now, the value for this metric will only look back 60s when it's only collected once a day.
=> fix(platform-summary): sign up rate needs longer alignment period to show in dashboard

k8s/helmfile/helmfile.yaml
Reverting because staging has insufficient resources for the defined limits/requests
This reverts commit 9f916d9eaa301b1327d616e6ad38085cfececfb6.
=> chore(revert): Revert "chore(elasticsearch): deploy ES 7.10.2 to staging (#978)"

Makefile
As we are now running GKE 1.26, this PR introduces using this k8s version locally too
=> chore(minikube): adjust k8s version to 1.26.5

tf/env/staging/cluster.tf
Ticket https://phabricator.wikimedia.org/T335853
As I assume this is what we need to in production as well, this adds 3 more nodes of the same type so we can have one ES pod per node.
=> chore(cluster): bump staging node count to 6 so it can accomodate 2 ES clusters

k8s/helmfile/helmfile.yaml
Ticket https://phabricator.wikimedia.org/T335854
This changes configuaration so that the non-deprecated way of declaring a single ES cluster is being used (as per https://github.com/wbstack/mediawiki/pull/362).
Diffs against production like
```diff
- name: MW_REDIS_PASSWORD                                                                                                                                                                      
valueFrom:                                                                                                                                                                                   
secretKeyRef: …
```
=> chore(mediawiki): new chart uses non-deprecated configuration

tf/env/production/error-rate-dashboard.tf, tf/env/production/es-prometheus-dashoard.tf, tf/env/production/incoming-traffic-dashboard.tf, tf/env/production/platform-summary-dashboard.tf, tf/env/production/uptime-latency-dashboard.tf, tf/env/production/volume-utilisation-dashboard.tf, tf/env/production/workload-technical-metrics-dashboard.tf, tf/env/staging/error-rate-dashboard.tf, tf/env/staging/platform-summary-dashboard.tf, tf/env/staging/uptime-latency-dashboard.tf, tf/env/staging/workload-technical-metric.tf
Starting 2023/07/20 some GCP Dashboards would start diffing dirty against main without any changes being made in the code. It seems this is due to API changes in GCP that stopped persisting this setting without raising errors or similar.
To work around this, remove all such settings.
Ticket: https://phabricator.wikimedia.org/T342525
=> fix(tf): color mode in xYCharts stopped persisting

k8s/helmfile/helmfile.yaml
Use a new version of the ES 6.8 chart, which has a new name. See https://github.com/wbstack/charts/pull/120
=> fix(helmfile): resolve ES Chart name conflicts

k8s/helmfile/env/staging/api.values.yaml.gotmpl
Testing what exactly happens if we turn this on
=> chore(api): enable stackdriver for staging api

k8s/helmfile/env/staging/api.values.yaml.gotmpl
This reverts commit 734ccc71fdd05db089b7f4b8c52f259f30a24791.
The stackdriver configuration does not work as intended.
```
[2023-07-27 13:13:29][okJavaIVgc7oIuCEmSFa4Nma2B2KCa6X] Processing: App\Jobs\MediawikiInit
In RequestWrapper.php line 368:
{
"error": {
"code": 403,
"message": "Permission 'logging.logEntries.create' denied on resource (or it may not exist).",
"status": "PERMISSION_DENIED",
"details": [
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"reason": "IAM_PERMISSION_DENIED",
"domain": "iam.googleapis.com",
"metadata": {
"permission": "logging.logEntries.create"
}
}
]
}
}
```
=> Revert "chore(api): enable stackdriver for staging api (#1018)"

k8s/helmfile/env/staging/api.values.yaml.gotmpl
This reverts commit 1f9ebfe660166aa778f2abc5e2a30bdc3043fef3.
Reverting again because it still fails. Probably further configuration
tweaks are needed.
```
[2023-07-27 15:26:01] production.ERROR: {
"error": {
"code": 400,
"message": "Log name (WBaaS Wikibase Dev) contains illegal
character. Allowed characters are alphanumerics and ./_-",
"status": "INVALID_ARGUMENT"
}
}
{"exception":"[object]
(Google\\Cloud\\Core\\Exception\\BadRequestException(code: 400): {
\"error\": {
\"code\": 400,
\"message\": \"Log name (WBaaS Wikibase Dev) contains illegal
character. Allowed characters are alphanumerics and ./_-\",
\"status\": \"INVALID_ARGUMENT\"
}
}
```
=> Revert "Revert "Revert "chore(api): enable stackdriver for staging api (#1018)" (#1019)" (#1020)"

k8s/helmfile/env/staging/api.values.yaml.gotmpl
#1018 did not disable logging, so we might want to try disabling everything but error reporting to see if this brings us what we want.
=> chore(stackdriver): enable stackdriver for error reporting only in staging

k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
Right now, throttling of signup would not be reported anywhere as stackdriver is still disabled.
=> chore(error-reporting): enable stackdriver error reporting for production

tf/env/staging/cluster.tf
Our current suspicion is that log backpressure is currently causing the cluster nodes to run out of ephemeral storage. If so, changing logging configfuration to allow for higher throughput might help.
Mostly interested in doing this in staging first to find out whether this requires a node replacement or can be done on the running node.
Diffs against staging like this
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:                                                                 
~ update in-place                                                                                                                                                                                        
Terraform will …
```
=> feat(cluster): update logging variant for staging

k8s/helmfile/env/local/api.values.yaml.gotmpl
It doesn't work locally and causes problems, so we disable it there
=> fix: disable stackdriver for local

tf/env/staging/cluster.tf
High Throughput logging uses 2 CPU per nodes, so let's try working around this by having 3 nodes twice as big.
=> chore(staging): scale down to 3 bigger nodes

k8s/helmfile/env/staging/elasticsearch-1.values.yaml.gotmpl
Right now it's not possible to schedule all pods in staging.
=> chore(elasticsearch): lower cpu limits in staging

k8s/helmfile/env/staging/elasticsearch-1.values.yaml.gotmpl
As the cluster is currently unable to assemble, let's maybe try this?
=> chore(elasticsearch): allow more CPU usage for staging master

k8s/helmfile/env/local/prometheus-elasticsearch-exporter-1.values.yaml.gotmpl, k8s/helmfile/env/production/prometheus-elasticsearch-exporter-1.values.yaml.gotmpl, k8s/helmfile/env/staging/prometheus-elasticsearch-exporter-1.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
Copies the existing exporter configuration. This targets the main elasticsearch service which only targets
the coordinating nodes.
Also add configuration with production values so that rolling forward to production will see minimal changes
After deploying this we need to follow up on the alerting and dashboards using ES metrics since we may now see places where data from both clusters are unintentionally mixed
=> local/staging: add prometheus-es-exporter for 7.10 cluster

k8s/jobs/changeReplicationPasswordOnSecondary.yaml, k8s/jobs/elasticSearchImportJob.yaml, k8s/jobs/forceSearchIndexFrom.yaml, k8s/jobs/rebuildQuantityUnitsJob.yaml, k8s/jobs/resetOtherSqlSecretsJob.yaml, k8s/jobs/resetRootSqlSecretJob.yaml, k8s/jobs/runAllMWJobsJob.yaml
There are currently >300 job objects floating around in our prod cluster. Are there any downsides of setting a ttl to them? I went for 30 days here
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
As an alternative we could add a script or something that edits this into the spec of existing jobs, so we could also opt for "cleaning" whenever we feel like its too much, instead of specifying it in beforehand (this would also come in handy to get rid of the current pile of old completed jobs)
=> chore(jobs): add ttl of 30 days to job templates

k8s/helmfile/env/production/elasticsearch-1.values.yaml.gotmpl
By setting this name to a custom value rather than the default we're able to more easily differentiate clusters in metrics etc.
=> k8s: Set 7.10 ES cluster name

k8s/helmfile/env/local/minio.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml, tf/env/local/secrets-minio.tf
This is prep work for moving backup transfer over to an S3 client. As of this PR, there are no consumers of the MinIO service.
1. Apply the changes and wait for the `minio` service to become ready
1. Install the [minio client](https://min.io/docs/minio/linux/reference/minio-mc.html)
1. Open a tunnel for the service:
```
kubectl port-forward svc/minio 9000:9000
```
1. Set an alias for your local cluster
```
mc alias set minikube "http://localhost:9000/" minio $(k get secrets/minio-credentials -o json | jq -r .data.rootPassword | base64 -d)
```
1. Poke around, e.g. create a new bucket and upload a file
```
mc mb test-bucket
echo "oh wow" > foo.txt
mc cp foo.txt minikube/test-bucket
mc cat minikube/test-bucket/foo.txt
```
=> feat(local): install minio object storage via helm chart

tf/env/local/namespaces.tf, tf/env/production/namespaces.tf, tf/env/staging/namespaces.tf
There's even more typos to be found here, the pod quotas still get assigned to the wrong namespace.
=> fix(tf): assign pod quotas to correct namespaces

k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml, tf/env/production/secrets-gcs.tf
=> chore(backup): update production sql backup to use s3 client

tf/env/production/platform-summary-dashboard.tf, tf/env/staging/platform-summary-dashboard.tf
It appears that the time time we stored our dashboard the json represention of the dashboard did not return a style object for text objects[0]. Now it always
returns empty ones.
This patch therefore adds them to avoid the perpetual-diff situation.
This patch should be a no-op on application and should remove TF perma-diff
[0] https://cloud.google.com/monitoring/api/ref_v3/rest/v1/projects.dashboards#text
=> tf:both fix platform summary error

k8s/jobs/changeReplicationPasswordOnSecondary.yaml, k8s/jobs/elasticSearchImportJob.yaml, k8s/jobs/elasticSearchInitJob.yaml, k8s/jobs/forceSearchIndexFrom.yaml, k8s/jobs/rebuildQuantityUnitsJob.yaml, k8s/jobs/resetOtherSqlSecretsJob.yaml, k8s/jobs/resetRootSqlSecretJob.yaml, k8s/jobs/runAllMWJobsJob.yaml
Not sure what happened to these yaml files but `ttlSecondsAfterFinished` needs to be in `.spec`
=> fix(jobs): move `ttlSecondsAfterFinished`

k8s/helmfile/env/local/mediawiki-139.values.yaml.gotmpl
decreases mediawiki pod replicas to 1 for the local environment
See https://github.com/wmde/wbaas-deploy/pull/1093
=> chore(local): set mediawiki replica count to 1

k8s/helmfile/env/local/api.values.yaml.gotmpl
My suggestion is to keep replica counts low for the local environment if it's not strictly needed, in order to make debugging and looking at logs easier
=> chore(local): set api replica count to 1

k8s/helmfile/env/staging/wbaas-backup.values.yaml.gotmpl
This should be helpful for debugging why #1092 fails
=> chore(staging): temporarily increase scratch disk size for backup

tf/env/production/secrets-gcs.tf
This was still missing in #1110
=> chore(tf): add production hmac secrets for gcs

k8s/jobs/forceSearchIndexFromTo.sh, k8s/jobs/forceSearchIndexFromTo.yaml
In favor of merging the copypasta script from #1081, I refactored the existing script to be able to use both the `--from` and `--to` options (only one of them works, as well as both, or none).
=> refactor(job): Add upper limit for forceSearchIndex

k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1126
=> Revert "chore(mediawiki): test fallback by disconnecting Elasticsearch on staging"

doc/adr/0009-terraform-style-conventions.md, doc/adr/index.md
This PR contains a new ADR, proposing to make use of the default terraform style conventions.
Additionally, all existing terraform code has been reformatted with `terraform fmt -recursive`.
=> (proposal) ADR: Terraform style conventions

k8s/helmfile/cert-manager.lock, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/helmfile.lock
https://github.com/wmde/wbaas-deploy/pull/1115 contained the wrong secret name for staging
- fix secret name
- update lockfiles
=> fix(staging): api deployment 

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
depends on: https://github.com/wbstack/api/pull/642
depends on: https://github.com/wbstack/charts/pull/127
This deploys API image 8x.22.1 via Chart 0.26.1
- the API image fixes recpatcha config https://github.com/wbstack/api/pull/642
- the new chart & values make use of the log level & app env settings
=> deploy(local/staging): api 8x.22.1

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/local/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/local/ui.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl, tf/env/local/secrets-recaptcha.tf
This PR cleans up some value files
- prod: api: `sitekeySecretName` gets removed (only UI needs it)
- local & staging: api: recaptcha3 secret secret name gets read from private.yaml 
- local: `external` block from api.values gets removed - honestly idk why it was even there
- local: ui: recaptcha3 site secret name gets read from private.yaml
- local: mw: recaptcha2 secrets name gets read from private.yaml
- local: rename recaptcha secrets to match staging/prod (`recaptcha-vN-secrets` vs `recaptcha-vN-dev-secrets`)
- **this will require to update your tfvars files**
=> chore(cleanup): recaptcha values

tf/env/production/cluster.tf
This reverts commit 97eae65c3e0ebdc57b790a9b93a019068733e235.
Reverting because applying this will cause node replacements, which shall be discussed first.
=> Revert "chore(prod): increase disk size (ephemeral storage) (#1179)"

k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
https://phabricator.wikimedia.org/T348148
Presumably increasing node disk size is not needed (#1179) for the backups but rather the size of the backup scratch volume.
=> chore(prod): increase scratch volume size for backups

k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
DIsables backup restore pod which prevents patching the sql backup deployments, also it shouldnt be running anyway
=> chore(prod): disable backup restore pod

tf/modules/CHANGELOG.md, tf/modules/monitoring/sql-backup-failure-alert.tf
https://phabricator.wikimedia.org/T348148#9228815
- Adds an alerting policy in case the scratch disk used by the logical SQL backups is getting to a critical usage (it will fill up eventually again and again, and this way we can act in advance)
- Fixes alerting policy for failed backups by setting the duration period to 24h (previously 24h 30m, which is invalid, max is 24h)
=> feat(monitoring): alert policy for SQL backup disk usage

k8s/helmfile/env/local/sql.values.yaml.gotmpl, k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T348842
These values are currently set manually in production where the job now passes again.
=> chore(sql): raise configuration values for open table caches

doc/adr/0011-handling-fqdns.md, doc/adr/index.md
An ADR about handling FQDNs, especially if they consinst of non-ASCII characters.
=> docs(adr): ADR no. 11 Handling FQDNs

tf/env/production/monitoring.tf, tf/env/staging/monitoring.tf
Deploys tf monitoring module v20 to production. Note: v19 was never deployed before this.
PR of v20: https://github.com/wmde/wbaas-deploy/pull/1185
=> chore(deploy): production: tf-module-monitoring-20

tf/env/production/namespaces.tf
Reducing these jobs since we seem to be seeing failures due to cluster timeouts
=> prod: reduce adhoc job parallelism

k8s/helmfile/env/production/elasticsearch-1.values.yaml.gotmpl
These nodes are failing to start and eventually being killed due to failing the liveness checks. This attempts to increase that number in the hope they eventually become live.
=> Increase elasticsearch-1 master liveness tolerance

k8s/helmfile/env/staging/elasticsearch-1.values.yaml.gotmpl
These appear to have been inadvertantly changed
due to the cascading change from production.
This commit fixes them at their current value
=> Keep staging elasticsearch-1 probes constant

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1213
Looks like this doesn't work with the updater:
```
Exception in thread "main" java.lang.IllegalStateException: Not a JSON Array: {"done":1,"eventFrom":632,"eventTo":633,"wiki_id":3,"entityIds":"Q7","updated_at":"2023-10-25T10:27:59.000000Z","created_at":"2023-10-25T10:27:59.000000Z","id":454,"wiki":{"id":3,"domain":"coffeebase.wikibase.dev","sitename":"coffeebase","deleted_at":null,"created_at":"2021-10-28T08:47:19.000000Z","updated_at":"2021-10-28T08:47:19.000000Z","description":null,"is_featured":0,"domain_decoded":"coffeebase.wikibase.dev","wiki_queryservice_namespace":{"id":3,"namespace":"qsns_610dc83f45","backend":"queryservice.default.svc.cluster.local:9999","wiki_id":3,"created_at":"2021-10-27T15:26:38.000000Z","updated_at":"2021-10-27T15:26:38.000000Z …
```
=> Revert "Staging+Local: Deploy new Platform API image 8x.25.3"

tf/env/local/secrets-recaptcha.tf, tf/env/local/variables.tf
Starting today, my local dev env would prompt for values like `recaptcha_v3_dev_site_key` which seem to have been replaced by `recaptcha_v3_site_key` equivalents quite a while ago.
=> fix(local): change variable declaration for recaptcha secrets

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
Ticket https://phabricator.wikimedia.org/T349887
Raising the requests for the pods lowers the chances of them being evicted by memory pressure on the host node.
Lowering the number of replicas again might help with reducing the number of DB connections being openend simultaneously.
=> chore(mw): raise memory requests, lower number of replicas

k8s/helmfile/env/local/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
This increased the allocated heap size used by the JVM in production only.
I followed the pattern used in ElasticSearch where the heap size is 50% of the memory that is generally available.
=> chore(qs-updater): increase jvm heap size

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
Seems we can still crash using the current config, so let's see if MediaWiki is just hungry.
=> chore(mediawiki): allocate more RAM and CPU for mediawiki web

tf/modules/CHANGELOG.md, tf/modules/monitoring/sql-backup-failure-alert.tf
This PR aggregates the log based metric that is used for the sql backup alerting.
=> fix(tf): sql alerting policy

k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1271
Looks like the code has a issue when WikiLifecycleEvents are missing:
```
[2023-11-17 11:39:00] staging.ERROR: Failure processing wiki então.carolinadoran.co for EmptyWikiNotification check: Trying to get property 'first_edited' of non-object                                                                   
[2023-11-17 11:39:00] staging.ERROR: Executing Job '' failed. {"exception":"[object] (Exception(code: 1): Executing Job '' failed. at /var/www/html/app/Providers/AppServiceProvider.php:32)                                               
[stacktrace] …
```
=> Revert "Staging+Local: Deploy new Platform API image 8x.27.0"

tf/modules/CHANGELOG.md, tf/modules/monitoring/sql-backup-failure-alert.tf
https://phabricator.wikimedia.org/T349817#9334181
increasing the alignment period of the logical sql backup alerting from 60s to 1h (current max) in order to prevent false alarms
=> tf-module-monitoring-22: improve sql backup alerting

k8s/helmfile/env/production/api.values.yaml.gotmpl
The CreateQueryserviceBatches job is now being OOM killed.
=> chore(api): allocate more resources to queue pods

k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
Ticket: https://phabricator.wikimedia.org/T352656
This should have no effects on the currently running setup and will just allow us to spawn K8s jobs that are based on the image at some point.
=> chore: update queryservice-updater image to latest version

tf/modules/CHANGELOG.md, tf/modules/monitoring/sql-backup-failure-alert.tf
release of `tf-module-monitoring-23`
Attempt to fix the alerting policy for sql logical backups. We suspect that the 1h alignment period is problematic as in combination with the absent trigger time it exceeds 24h 30m, which is maybe why it is not working.
=> attempt to fix sql logical backup alerting policy

k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl, k8s/helmfile/env/staging/wbaas-backup.values.yaml.gotmpl, tf/env/production/monitoring.tf, tf/env/staging/monitoring.tf
**This PR needs to be reverted after testing** 
The purpose of this is to "disable" the sql backup cronjobs by using only a single date in November. We want to see if the change of the alerting policy in #1323 fixes it (this way we can test staging and prod at the same time since we saw strange differences here in the past).
- use `tf-module-monitoring-23` on staging and prod
- "disable" the backup cronjob for staging and prod
=> Test SQL alerting policy

k8s/helmfile/env/production/wbaas-backup.values.yaml.gotmpl
The test of `tf-monitoring-23` was successful:
- [Incident on staging](https://console.cloud.google.com/monitoring/alerting/incidents/0.n5swu2bvw2kl?project=wikibase-cloud&pageState=(%22interval%22:(%22d%22:%22P1D%22,%22i%22:(%22s%22:%222023-12-14T23:34:08.000Z%22,%22e%22:%222023-12-15T08:32:54.837Z%22)))) 
- [Incident on production](https://console.cloud.google.com/monitoring/alerting/incidents/0.n5sz53jpj76e?project=wikibase-cloud&pageState=(%22interval%22:(%22d%22:%22P1D%22,%22i%22:(%22s%22:%222023-12-15T01:15:08.000Z%22,%22e%22:%222023-12-15T08:32:54.790Z%22))))
This PR re-enables the cronjob schedules and keeps the new module in use.
=> Re-Enable SQL backups

tf/modules/CHANGELOG.md, tf/modules/monitoring/platform-summary.tf
Platform stats went missing since shipping #1329 as the deployment objects now have different labels, and the query in this module would yield no results.
=> fix(tf-monitoring): k8s labels for api queue have changed

k8s/helmfile/helmfile.yaml
Looks like when we moved to the new cluster we accidentally overlooked this. It's useful to have in order to diagnose issues and monitor the cluster.
Bug: T354048
=> production: Enable Elasticsearch Prometheus Exporter

k8s/helmfile/env/production/prometheus-elasticsearch-exporter-1.values.yaml.gotmpl
The exporter is currently being killed due to lack of memory let us try increasing this
=> production: increase ES Prometheus exporter memory

k8s/helmfile/env/production/prometheus-elasticsearch-exporter-1.values.yaml.gotmpl
Bumping these limits excessively high; they
really ought not to stay here but I want some
data to try and gracefully resolve T354048
particularly given I'm the only engineer here today
=> production: bump ES Prom Exporter limits

tf/modules/CHANGELOG.md
In #1372 an incorrect changelog entry was added as an existing tag was missing from the changelog.
=> fix: tf-module-buckets-2 tag was missing from CHANGELOG

tf/env/production/buckets.tf, tf/modules/CHANGELOG.md, tf/modules/buckets/main.tf
The HMAC keys that are currently in use by the SQL backup suffer from the same problem as #1372 as they grant the keys permissions beyond the bucket in use for backups.
This PR adds a properly scoped key to the `buckets` terraform module. In a second PR we can remove the old keys and start consuming these ones in the respective environments.
=> fix: add iam members and hmac keys for SQL backups in buckets module

tf/modules/buckets/main.tf
#1377 contained a mistake where the resource name for the HMAC keys would be duplicated.
=> fix(tf): resource name is used twice in buckets module

tf/modules/buckets/main.tf
Reverts wmde/wbaas-deploy#1378
Reverting this as it's still broken and I don't have the capacity to fix it right now.
=> Revert "fix(tf): resource name is used twice in buckets module"

tf/env/production/buckets.tf, tf/modules/CHANGELOG.md, tf/modules/buckets/main.tf
Reverts wmde/wbaas-deploy#1377
Reverting this as it's still broken and fixing will need to be postponed.
=> Revert "fix: add iam members and hmac keys for SQL backups in buckets module"

k8s/helmfile/env/production/kube-prometheus-stack.values.yaml.gotmpl, k8s/helmfile/env/staging/kube-prometheus-stack.values.yaml.gotmpl
So far this seems to work as intended in staging (i.e. no rise in the number of ingested prometheus samples) after deploying #1405 and triggering a rebuild at 12:21 chart time:
=> chore(kube-state-metrics): also skip qs-jobs namespace in production

k8s/helmfile/env/local/kube-prometheus-stack.values.yaml.gotmpl
Tweak the local setup to only override the grafana and prometheus config leaving the other services to inherit from prod.
This enables the kubeStateMetrics
Bug: T356049
=> chore(local): set prometheus operator to be more prod-like

k8s/helmfile/env/local/kube-prometheus-stack.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml, k8s/helmfile/prometheus-operator.yaml
This updates the prometheus stack version through
many major versions.
It also updates the prometheus operator CRDs that
kube-prometheus-stack relies on from 2.0.0 to 9.0.0
While the README[1] lists multiple manual actions required for the kube-prometheus-stack update it appears that the only ones that apply to us are the CRD updates.
I also tested if the CRD updates appear to be backwards compatible and to a very cursory test the older version of kube-prometheus-stack still works and can be fully removed and reapplied to the cluster.
[1] https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
=> k8s:local upgrade kube-prometheus-stack Chart to 56.6.2

k8s/helmfile/helmfile.yaml
This has now been superceded by prometheus-elasticsearch-exporter-1
We must mark as uninstalled before removing the reference to the release in a follow-up commit to actually remove the relevant resources
=> k8s: removed unused old elasticsearch exporter from all environments

k8s/helmfile/helmfile.yaml, k8s/helmfile/prometheus-operator.yaml
This does not update the GKE prometheus-engine/prometheus image. I propose doing this as a separate second step after the rest of the stack is present in both staging and production
Bug: T356049
=> k8s:staging upgrade kube-prometheus-stack Chart to 56.6.2

tf/modules/CHANGELOG.md, tf/modules/monitoring/metric-alarms.tf
Ticket: https://phabricator.wikimedia.org/T356254
In staging this created an alarm like this:
=> feat(monitoring): add alarm when number of available es shards is low

k8s/helmfile/istio-control-plane.yaml, k8s/helmfile/prometheus-operator.yaml
It appears that without these present helmfile uses the default environment (and thus kubecontext) for applying changes due to these subhelm files.
This is a big issue; it means that you may accidentally apply to the wrong environment and there will be no hint
=> fix(k8s): add environment definitions to subhelmfiles

k8s/helmfile/helmfile.yaml
This should give us one thing less to wait for when `helmfile` is running.
=> chore: elastic helm repo is unused

k8s/helmfile/helmfile.yaml, k8s/helmfile/prometheus-operator.yaml
This does not update the GKE prometheus-engine/prometheus image. I propose doing this as a seperate second step after the rest of the stack is present in both staging and production
Bug: T356049
=> k8s:production upgrade kube-prometheus-stack Chart to 56.6.2

k8s/helmfile/helmfile.yaml
This patch hints to helm the capabilities to make the templating behave properly[1] when using .Capabilities.APIVersions.Has in charts.
[1] - https://github.com/helm/helm/issues/10760
Bug: T358468
=> fix(k8s): helm diff in kube-prometheus-stack-operator ClusterRole

.tool-versions
This adds a `.tool-versions` file.
The concept of this file stems from the tool `asdf`: https://github.com/asdf-vm/asdf
https://asdf-vm.com/manage/configuration.html
The idea is that even if you don't use this tool, we can use this file as a reference of the recommended versions of the cli tools we are using.
For this PR, please check the versions of the tools you currently use and suggest newer versions if present on your system.
=> add `.tool-versions`

k8s/helmfile/env/staging/api.values.yaml.gotmpl
Jobs stopped running in staging after deploying #1481 so I disable Hoizon until I figured out why.
=> chore(api): disable horizon in staging

k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
We want to confirm if the CPU exhaustion on the queryservice is due to the updater or due to other traffic.
Bug: T361551
=> production: reduce queryservice-updater replica 0

k8s/helmfile/env/local/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
Ships https://github.com/wbstack/queryservice-gateway/pull/164 and https://github.com/wbstack/charts/pull/142
=> chore(qs-gateway): update image to 2.3 and update chart

k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl
This shall be deployed before https://github.com/wmde/wbaas-deploy/pull/1530 and reverted again once it's safe to say the QueryService is still working correctly
=> chore(queryservice-updater): temporarily scale down to 0

k8s/helmfile/env/local/queryservice.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1536
It seems this introduces a lag in the updater for reasons I don't understand yet.
=> Revert "chore(wdqs): use 0.3.137-wbstack.1 in staging and local"

k8s/helmfile/argo-cd.yaml
When deploying #1545 I encountered this warning:
```
WARNING: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part
```
=> argo: yaml hotfix

doc/deployments/argocd.md, k8s/helmfile/env/local/argo-cd-base.values.yaml.gotmpl
This PR adds http ingress configuration for the local minikube deployment of argocd: http://argo.wbaas.localhost/
=> argo: add local ingress conf

tf/env/staging/monitoring.tf, tf/modules-next/monitoring/elasticsearch-pv.tf, tf/modules-next/monitoring/elasticsearch.tf, tf/modules-next/monitoring/main.tf, tf/modules-next/monitoring/metric-alarms.tf, tf/modules-next/monitoring/platform-summary.tf, tf/modules-next/monitoring/providers.tf, tf/modules-next/monitoring/queryservice-pv.tf, tf/modules-next/monitoring/replication-lag-alert.tf, tf/modules-next/monitoring/sql-backup-failure-alert.tf, tf/modules-next/monitoring/sql-pv.tf, tf/modules-next/monitoring/variables.tf
This follows the pattern of ADR 12 and introduces a "next" version of the monitoring module.
This next version of the monitoring module contains the mostly renamed not_edited_last_90_days and edited_last_90_days as well as the new total_properties_count and total_items_count as default log based metrics to be created.
This new module is sourced and the overriding of
platform_summary_metrics variable is removed since it is no longer necessary
Bug: T364452
Bug: T314481
=> feature(staging): add additional platform summary metrics

tf/modules-next/monitoring/metric-alarms.tf
This is necessary to prevent multiple alerts from firing (e.g. for each indvidual index)
=> fix:(staging) Add reducer to Elasticsearch Alarms

tf/env/production/monitoring.tf
This patch removes an override that prevents the default platform summary metrics from being using in the module
=> fix: production TF remove monitoring param override

tf/env/production/platform-summary-dashboard-json.json, tf/env/staging/platform-summary-dashboard-json.json
It seems #1633 did not contain the changes it should have contained. This is another attempt at porting the manually edited dashboard.
=> chore(dashboards): update platform summary dashboards

k8s/helmfile/env/production/api.values.yaml.gotmpl
Reverts wmde/wbaas-deploy#1647
Applying the migration failed
```
In Connection.php line 824:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '647' for key 'wiki_lifecycle_events_wiki_id_unique' (Connection: mysql, SQL: alter table `wiki_lifecycle_events` add unique `wik  
i_lifecycle_events_wiki_id_unique`(`wiki_id`))                                                                                                                                                           
In Connection.php line 587:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '647' for key 'wiki_lifecycle_events_wiki_id_unique'  
```
which means the cleanup logic must somehow leave multiple items for certain wikis.
=> Revert "Production: Deploy new Platform API image 10x.8.4"

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
The `status.wikibase.cloud` redirect was broken since merging #1638. It seems this was caused by including https://github.com/kubernetes/ingress-nginx/pull/10393, silently removing the required annotation from the ingress.
This PR enables the setting again, restoring behavior as of #1632
=> fix(redirects): later chart versions disable server snippets by default

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl
This patch attempts to increase the number of replicas of mediawiki web to see if spreading the load more thinly results in less restarts of these web pods
Bug: T368360
=> production(mediwiki): increase web replica count

Makefile
This increases the k8s version to match the GKE one in production.
Shouldn't need any more precise review (obviously this won't start a new cluster until make `minikube-start` is called on each engineer's machine.
As discussed in the daily this means it's probably also a good point for engineers to remember to update their `kubectl` client
Bug: T369255
=> chore(minikube): increase k8s version to 1.28.9

.tool-versions
After the increase in kubernetes version both automatically on
GKE but also locally in #1664 it would be nice to update this version
we should keep it close to production versions and always within one
minor version.
Nothing
None
See: https://github.com/wmde/wbaas-deploy/pull/1664#pullrequestreview-2158383591
=> chore(k8s): bump kubectl version in tool-versions

charts/superset/templates/statefulset.yaml
The SecurityContext spec cannot contain fsGroup and fsGroupChanngePolicy as per the api reference[1]
This only seems to be an issue on some developers
machines but it prevents deploying code.
Given that this is invalid k8s yaml it would be better removed
[1] - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#securitycontext-v1-core
If anyone has any more ideas about *why* some developers' setups happily ingest this invalid spec I'd be interested to hear.
We talked about this in person at some length during the team week on the afternoon of 2024-07-10
=> fix(superset chart): Remove invalid SecurityContext

k8s/helmfile/env/local/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
Uses the chart introduced in wbstack/charts#145
This commit also adds a value file for future use in production. The max value for local and staging are set to 2 to keep unnecessary scaling to a minimum while also enabling us to see the effect.
It is set to 5 for production because this gives some headroom above the currently defined 3.
No particular help needed just a general eye for mistakes.
I'd also happily hear feedback on the max values.
Bug: T368360
=> chore(mediawiki): enable HPA for MW in local and staging

k8s/helmfile/helmfile.yaml
As a follow up to #1704 this enables using the new MW chart with an HPA for production.
Nothing but a quick glance for a mistake
Bug: T368360
=> production feat(mediawiki): add HPA for web

bin/generate-values
=> add verbose output if running in CI

.github/workflows/check-generated-values.yml
This uses actions to setup helmfile and yq similar to wbstack/ui#859
paired with @deer-wmde
=> gh-action: use actions for check-generated-values.yml

.tool-versions
we noticed problems when running different opentofu versions so here is the new recommended version we should use
=> .tool-versions: bump opentofu version

k8s/helmfile/env/local/sql.values.yaml.gotmpl, k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
We bumped `table_open_cache` and `table_definition_cache`. Reasons:
- We think the `PlatformStatsSummaryJob` from the `api` opens many tables. The more wikis, the more tables are opened so as the wikis number grows, we need more room for tables to be opened at the same time.
- We think this number should be >3 times the number of wikis (incl. deleted wikis).
- So we should now have around 300 wikis headroom.
- Just try and see if it fixes the problem
- Paired with @tarrow and @deer-wmde on this topic.
Bug: T373448
=> Bump table_open_cache and table_definition_cache

k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl
In order to make wbcloud lives easier I configured a read-only access for ArgoCD where you do not need to log in in order to inspect argo resources with its ui.
I'm not sure I did this right, but it seems to do the trick. Here are some docs: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
=> argo: anonymous read-only access

Makefile, bin/argocli, doc/deployments/argocd.md
Adds some makefile targets to sync argo applications (ui and all, via app-of-apps)
and to list available argo applications
This uses a simple bash script `./bin/argocli` that executes the argocd cli client in the application controller pod. This can also be used on its own to use the cli tool in a generic way.
https://phabricator.wikimedia.org/T360876
https://phabricator.wikimedia.org/T360876#10001045
=> (argo) add makefile targets

tf/env/production/platform-summary-dashboard-json.json, tf/env/staging/platform-summary-dashboard-json.json
1. On the Platform Summary dashboard in Google Cloud the scorecards total items and total properties
are configured to 50th percentile instead of Mean and therefore show incorrect numbers not matching the charts ?
2. I made the change on the google cloud dashboard and downloaded the json with
which I then updated these files?
Please confirm this has no bomb in it and can be deployed to production.
https://phabricator.wikimedia.org/T369347
=> Change scorecard values for total item and properties from 50th percentile to Mean

k8s/helmfile/env/staging/platform-nginx.nginx.conf
This change routes all wiki traffic that goes to the platform-nginx for https://anton2.wikibase.dev/ to the alpha mediawiki deployment.
This allows us to push specific images there for unusual/dangerous configurations.
Right now there is are no values change in git for this unusual configuration and they are being managed by manually altering the images that are present.
Currently being tried under "dibs" on staging. You could check that this is indeed working as expected by confirming that traffic is going to the alpha wiki.
Almost none, let me know what you think @rosalieper 
Bug: T374336
=> staging: platform-nginx route PMs wiki to alpha mediawiki

k8s/helmfile/helmfile.yaml
For some reason I thought we need to set this to `installed: false` in order to stop helmfile from redeploying this in case argocd is doing the deployment. That assumption seems to be false though.
We could also get rid of this part of the `generate-values` script then, but on the other hand it also doesn't harm us: https://github.com/wmde/wbaas-deploy/blob/e82d4703717c8b16ca03f21110c2561835646088/bin/generate-values#L47-L50
=> helmfile: remove `installed: false` for ui

k8s/helmfile/env/local/argo-cd-base.values.yaml.gotmpl, k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl
A while ago I configured different banners for the different environment argocd runs in. For some reason it stopped working some time, now I found the reason (and I fixed the URL for local env)
=> argocd: fix environment banner

k8s/helmfile/env/production/platform-nginx.nginx.conf
n.b. this doesn't impact queryservice
We want to try this in order to see if it stops what appears to be cascading outages.
Paired with @deer-wmde on this.
Bug: T375866
=> production: reduce general platform nginx to 10s

k8s/helmfile/env/production/platform-nginx.nginx.conf
Reverts wmde/wbaas-deploy#1787
https://phabricator.wikimedia.org/T375866
This seems to make things worse or at least doesnt help much, appearantly
=> Revert "production: reduce general platform nginx to 10s"

k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl
https://phabricator.wikimedia.org/T375874
as a first step we only lift cpu limits for mw resources and will observe the effect
=> lift cpu limits for mediawiki resources

k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
https://phabricator.wikimedia.org/T375874
lift cpu limits for sql deployments, could be the next step after https://github.com/wmde/wbaas-deploy/pull/1790
=> lift sql cpu limits

k8s/helmfile/helmfile.yaml
Update api chart version for all environment
Link to Phabricator
Bug: [T375268](https://phabricator.wikimedia.org/T375268)
=> Use api 0.32.0

k8s/helmfile/env/local/ingress-nginx.values.yaml.gotmpl
Setting up a local cluster from scratch occasionally fails due to the following error:
```
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.98.30.137:443: connect: connection refused
```
=> fix: creating local cluster fails on Nginx webhook

k8s/argocd/local/api.values.yaml, k8s/argocd/local/ui.values.yaml, k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/local/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/local/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/local/platform-nginx.values.yaml.gotmpl, k8s/helmfile/env/local/ui.values.yaml.gotmpl
Setting up a local cluster from scratch fails on multiple releases with errors similar to the following:
```
Deployment.apps "ingress-nginx-controller" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "100m": must be less than or equal to cpu limit of 0
```
This patch restores previous CPU limits for affected releases.
=> fix: creating local cluster fails on CPU limit

k8s/helmfile/cert-manager.yaml
Reverts wmde/wbaas-deploy#1804
This didn't have the impact we were expecting on staging. There were still a large amount of pointless-ish looking logs
=> Revert "reduce cert manager log level"

k8s/helmfile/argo-cd.yaml, k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl
This updates argocd from v2.10.7 to v2.12.5
by using chart v7.6.11
https://github.com/argoproj/argo-helm/blob/argo-cd-7.6.11/charts/argo-cd/Chart.yaml
As far as I can see no config adjustments need to happen: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.10-2.11/
=> update argo to 2.12.5

k8s/argocd/production/ui.values.yaml, k8s/argocd/staging/ui.values.yaml, k8s/helmfile/env/production/ui.values.yaml.gotmpl
It appears that null cpu limits don't seem to work well and result in argocd constantly syncing
Instead it is better to totally omit them
This commit will be followed up by one for the API
Bug: T378328
=> argo: staging and prod remove null cpu limits

k8s/argocd/production/api.values.yaml, k8s/argocd/staging/api.values.yaml, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
Also remove null cpu limit from api.
This should allow argo to smoothly sync
Bug: T378328
=> argo: api staging and prod remove null cpu limits

.github/workflows/check-generated-values.yml, k8s/argocd/local/app-of-apps.values.yaml, k8s/argocd/local/redis.values.yaml, k8s/argocd/production/redis.values.yaml, k8s/argocd/staging/redis.values.yaml, k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T375195
- adds generated redis value files
- increase resource values
=> local: argo redis deployment

k8s/helmfile/helmfile.yaml
Unfortunately 1.0.8 was mistakenly configured to use https://github.com/wbstack/charts.git rather than
https://wbstack.github.io/charts and therefore wasn't correctly parsing the chart without a path. 1.0.9 is a fixup for this that uses the correct repoURL
Bug: T375195
=> helmfile: fixup for argocd-config 1.0.8

k8s/helmfile/env/staging/argo-cd-base.values.yaml.gotmpl
We seem to regularly be being OOM killed so this commit increases the request to match the limit of 512Mi
Bug: T375195
=> staging(argocd): increase memory request

k8s/argocd/production/redis.values.yaml, k8s/argocd/staging/redis.values.yaml, k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl, k8s/helmfile/env/production/elasticsearch-2.values.yaml.gotmpl, k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/env/production/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/production/platform-nginx.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-ui.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice-updater.values.yaml.gotmpl, k8s/helmfile/env/production/queryservice.values.yaml.gotmpl, k8s/helmfile/env/production/redis.values.yaml.gotmpl, k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/production/superset.values.yaml.gotmpl, k8s/helmfile/env/production/tool-cradle.values.yaml.gotmpl, k8s/helmfile/env/production/tool-quickstatements.values.yaml.gotmpl, k8s/helmfile/env/production/tool-widar.values.yaml.gotmpl, k8s/helmfile/env/staging/elasticsearch-2.values.yaml.gotmpl, k8s/helmfile/env/staging/mediawiki-139.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice-gateway.values.yaml.gotmpl, k8s/helmfile/env/staging/queryservice.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
This commit removes cpu limites rather than setting them to null
I notive on a number of occasions this causes issues with the k8s api which treats null as 0 and then results in errors applying a request that is more than 0.
Instead this simply doesn't set any limit
=> helmfile: remove null cpu limits

bin/generate-values, k8s/helmfile/helmfile.yaml, k8s/helmfile/only-for-argo-value-generation.yaml
This commit seeks to remove services that are now fully migrated to argo from the main helmfile.yaml.
This should prevent running `make apply` from showing phantom diffs where argo has already enacted the change but helm hasn't yet recorded that change in its secrets.
The github actions reference `generate-values`  and not the specific helmfile yaml so this patch should not require any updates to either [check-generated-values](https://github.com/wmde/wbaas-deploy/blob/main/.github/workflows/check-generated-values.yml) or the image bumping scripts from [api](https://github.com/wbstack/api/blob/main/.github/workflows/docker.build.yml#L88) or [ui](https://github.com/wbstack/ui/blob/main/.github/workflows/docker.build.yml#L80).
=> k8s: Remove Argo managed services from helmfile

k8s/argocd/production/redis.values.yaml, k8s/argocd/staging/redis.values.yaml, k8s/helmfile/env/production/redis.values.yaml.gotmpl
It appears that while the replica limit was removed in #1788 the master limit was overlooked. This also removes it here also
Discovered as an issue due in #1869
Bug: T380777
=> redis: staging and production remove master cpu limit

k8s/helmfile/env/production/argo-cd-base.values.yaml.gotmpl
this commit removes the resources setting that appears to be inadvertantly re-enabling the dex server and config after it was attempted to be disabled at the top of
production/argo-cd-base.values.yaml.gotmpl
Bug: T381960
=> argo: disable dex in all environments

k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T378691
follow up to https://github.com/wmde/wbaas-deploy/pull/1868
it was missing using the new chart
=> use clusterissuer chart 0.2.0

.gitignore, Makefile, doc/local-dev-env.md, k8s/helmfile/env/local/argo-cd-base.values.yaml.gotmpl, k8s/helmfile/env/local/certificates.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T378691
This adds a makefile target to easily export the local CA certiface that gets used to self-sign the locally used TLS certificates. This can get used to circumvent browser warnings.
- also adds config to issue local argo a certificate
=> local tls: add ca cert export and documentation + argo cert

Makefile
This adds Makefile targets for skaffolding cradle, quickstatements and widar. The skaffold configuration already existed.
=> feat: add Makefile targets for tools

tf/env/production/monitoring.tf
This commit tweaks the log based metric to more specifically target just incoming requests rather than also error log lines etc. from nginx
This uses a regex that should match an ipv4, a dash, the possible
- or $remote_user and the [ at the start of the timestamp.
Bug: T385969
=> tf(prod): clarify production-site-request-count

doc/managing-google-cloud-resources.md, tf/env/production/es-prometheus-dashboard-json.json
Like in #1635 the JSON format of the dashboards seems to have drifted.
I repeated the process used there to download the latest json using the api explorer.
I also added a short doc about this
Bug: T386614
=> prod(tf): fix permenant dashboard diff

tf/env/production/monitoring.tf
This copies the staging log based metric
This commit even further refines the log based metric. Specifically it now isolates the it to only contain wbaas-3 metrics.
Secondly it tightens the label extraction. This is specifically to target the edge case of things like urls included in user agent strings
Bug: T385969
=> prod(tofu): refine production-site-request-count

k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T383335#10591561
uses https://github.com/wbstack/charts/pull/187 in order to deploy only the clusterissuer needed for the current environment
=> use wikibase-cloud-clusterissuers v0.3.0

k8s/helmfile/env/production/elasticsearch-2.values.yaml.gotmpl
Looking at the last 12 weeks we didn't use more than 140m cpu for elasticsearch master. Let's massively reduce the request to 300m.
Bug: T390698
=> prod(tf): reduce elasticsearch-data cpu request

k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T390823
4.12.1 turned out to be incompatible with our api ingress path configs
```
Failed sync attempt to : one or more synchronization tasks completed unsuccessfully, reason: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: ingress contains invalid paths: path /()(.*) cannot be used with pathType Prefix path /api(/|$)(.*) cannot be used with pathType Prefix (retried 5 times).
```
4.11.5 still contains the security fixes and seems to work with the config
=> downgrade nginx-ingress to 4.11.5

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl, k8s/helmfile/helmfile.yaml
use the newer ingress-nginx chart again (compare https://github.com/wmde/wbaas-deploy/pull/2044)
and disable strict path types to keep api and ui ingress path config working
=> use ingress-nginx 4.12.1 with less strict config

k8s/argocd/production/api.values.yaml, k8s/helmfile/env/production/api.values.yaml.gotmpl
Looking at the last 90 days we used less than 1m cpu
This drops to reflect that
Bug: T390698
=> prod(k8s): reduce api-queue cpu request

k8s/argocd/local/api.values.yaml, k8s/argocd/production/api.values.yaml, k8s/argocd/staging/api.values.yaml, k8s/helmfile/env/production/api.values.yaml.gotmpl
Looking at the last 90 days weeks we used a rough, eyeballed average of 250m cpu.
This proposes setting the request to 80% of that
Bug: T390698
=> prod(k8s): reduce api-backend cpu request

k8s/helmfile/env/production/sql.values.yaml.gotmpl
Looking at the last 90 days we used an average of 380m.
This proposes setting the request to just above that given how highly we value responsive sql
Bug: T390698
=> prod(k8s): reduce sql-secondary cpu request

k8s/helmfile/env/production/sql.values.yaml.gotmpl
Looking at the last 90 days we used an average of 90m.
This proposes setting the request to just above that given how highly we value responsive sql
Bug: T390698
=> prod(k8s): reduce sql-primary cpu request

k8s/helmfile/env/staging/private.yaml
As I was writing some documentation on increasing sql disk storage, I tried this on staging - turns out you can't decrease anymore, so here's the update to keep our conf in sync.
> [!IMPORTANT]
> Before applying this, deleting the StatefulSets is necessary ([docs](https://github.com/wmde/wbaas-deploy/blob/3f0e015dbc5028baecfc4d34726c969cc9ae83d5/doc/increasing-sql-storage.md))
>   - `kubectl delete statefulset sql-mariadb-primary --cascade=orphan`
>  - `kubectl delete statefulset sql-mariadb-secondary --cascade=orphan`
=> increase staging sql disks (slightly)

k8s/helmfile/env/production/sql.values.yaml.gotmpl, k8s/helmfile/env/staging/sql.values.yaml.gotmpl
related: https://phabricator.wikimedia.org/T390823
Currently SQL StatefulSets can not come back up due to invalid cpu limits
```
Warning  FailedCreate  2m6s (x30 over 3h27m)  statefulset-controller  create Pod sql-mariadb-primary-0 in StatefulSet sql-mariadb-primary failed error: Pod "sql-mariadb-primary-0"
is invalid: spec.containers[0].resources.requests: Invalid value: "750m": must be less than or equal to cpu limit of 0
```
=> sql statefulsets: remove cpu limits

tf/env/production/cluster.tf
This patch adds a new identical node pool to production without highthroughput logging.
We have very rarely in the last 2 weeks exceeded the 100KiB/s limit for the default logging.
Let's try to return to this and see if we can reduce the logspam.
This patch will be followed up with a second one to remove the old node pool
Bug: T390698
=> prod(tf): add node pool without highthroughput logging

k8s/helmfile/env/staging/elasticsearch-2.values.yaml.gotmpl
Since we experience some struggles with resource allocation on staging[1], I looked into workloads where we could reduce requests. ES nodes seems like good candiates. This also removes the cpu limit setting that is probably misconfigured
[1] currently sql replica is struggling to allocate enough cpu: `Warning  FailedScheduling   2m7s (x237 over 19h)   default-scheduler   0/3 nodes are available: 1 Insufficient cpu, 2 Insufficient memory. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.`
=> staging: reduce ES requests

tf/env/staging/providers.tf
Regular update: perhaps to resolve issue seen in #2064 
Bug: T391569
=> staging(tf): bump google tf provider to 6.29.0

k8s/helmfile/env/staging/sql.values.yaml.gotmpl
follow up to https://github.com/wmde/wbaas-deploy/pull/2065
because now ES doesnt get its piece of the pie: `Warning  FailedScheduling   2m7s (x237 over 19h)   default-scheduler   0/3 nodes are available: 1 Insufficient cpu, 2 Insufficient memory. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.`
=> staging: reduce sql cpu requests

tf/env/production/cluster.tf
Reverts wmde/wbaas-deploy#2074
This also doesn't work:
```
google_container_node_pool.wbaas-3_compute-pool-3: Creating...
╷
│ Error: error creating NodePool: googleapi: Error 404: Not found: projects/wikibase-cloud/locations/europe-west3/clusters/wbaas-3.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0xc20a89de1cda02ea"
│   }
│ ]
│ , notFound
│
│   with google_container_node_pool.wbaas-3_compute-pool-3,
│   on cluster.tf line 62, in resource "google_container_node_pool" "wbaas-3_compute-pool-3":
│   62: resource "google_container_node_pool" "wbaas-3_compute-pool-3" {
│
╵
make: *** [Makefile:92: apply-production] Error 1
```
=> Revert "prod(tf): add node pool without highthroughput logging"

tf/env/production/cluster.tf
To try and reduce costs we could try a smaller cluster and a new (n4) cpu type.
This commit does make both changes at once but that will mean less downtime while we rotate nodes than trying each option independently.
For reference at this moment wbaas-3 has a peak of 4.73 vcpu request on one node and a 42.2GB mem request on another so this should still leave us with quite some headroom
Bug: T390698
=> prod(tf): try n4-highmem-8 node pool

tf/env/production/cluster.tf
Reverts wmde/wbaas-deploy#2082
SQL and Redis failing to come up
```
vc-b2c41f80-5c5d-4909-87a5-1af2599801f9" : rpc error: code = InvalidArgument desc = Failed to Attach: failed when waiting for zonal op: rpc error: code = InvalidArgument desc = operation operation-1744366839499-6327e0dd38905-8ec8c388-a57b5eb6 failed (UNSUPPORTED_OPERATION): [pd-ssd, n4-highmem-8] features are not compatible for creating instance
```
=> Revert "prod(tf): remove old n2 node pool"

tf/env/production/cluster.tf
Reverts wmde/wbaas-deploy#2081
Back to n2 cluster on prod for a while; probably most sensible to try moving to n4 on staging
=> Revert "prod(tf): try n4-highmem-8 node pool"

tf/modules/monitoring/sql-pv.tf
https://phabricator.wikimedia.org/T390823
https://phabricator.wikimedia.org/T390566
In a post-mortem around the recent database outage a decision was made to lower the threshold of the sql pv utilization alert to 70%: https://docs.google.com/document/d/1iP1Gf1CNTvl7beV0NJvMzXtbczGpWkKoH8Hcmc5gg5w/edit?tab=t.0
=> tf: lower sql disk alert threshold to 70%

k8s/argocd/production/redis-2.values.yaml, k8s/argocd/production/redis.values.yaml, k8s/helmfile/env/production/redis.values.yaml.gotmpl
Values determined by looking at last 2 weeks resource utilisation data and selecting a value near the peak.
Also removes an errant cpu limit on the redis-2 master
Bug: T390698
=> prod(k8s): reduce redis cpu requests

k8s/helmfile/env/production/elasticsearch-2.values.yaml.gotmpl
Values determined by looking at last 2 weeks resource utilisation data and selecting a value near the peak.
Bug: T390698
=> prod(k8s): reduce ES cpu requests

k8s/argocd/local/api.values.yaml, k8s/argocd/staging/api.values.yaml, k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
This reverts commit 8be64cd542fdb139efe1e9be1bb627c5e1eeddff.
```
Normal   Scheduled  70s                default-scheduler  Successfully assigned default/api-pre-install-artisan-setup-2cjm9 to gke-wbaas-2-compute-pool-2-ee90b82c-hg54            
Normal   Pulling    29s (x3 over 70s)  kubelet            Pulling image "ghcr.io/wbstack/api:10x.19.0"                                                                             
Warning  Failed     29s (x3 over 69s)  kubelet            Failed to pull image "ghcr.io/wbstack/api:10x.19.0": rpc error: code = NotFound desc = failed to pull and unpack image "g
hcr.io/wbstack/api:10x.19.0": failed to resolve reference "ghcr.io/wbstack/api:10x.19.0": ghcr.io/wbstack/api:10x.19.0: not found                                                    
Warning …
```
=> Revert "staging/local: use api image 10x.19.0 (#2106)"

doc/local-dev-env.md
Seems like this step is not optional anymore with recent browser versions and having the local CA cert imported is required for the local dev env
=> docs: clarification on local ssl cert

k8s/helmfile/helmfile.yaml
https://phabricator.wikimedia.org/T395231
- requires https://github.com/wbstack/charts/pull/194
- should be merged after https://github.com/wmde/wbaas-deploy/pull/2134
=> use cloud-clusterissuers chart v0.3.1 everywhere

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
We're seeing a number of sites now bumping off the limiter and that's still enough to take the DB down.
This patch drops it back down again
Bug: T399439
=> k8s(ingress-nginx): tighten per site rate limits

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
This add a new limit_req_zone that only applies to ips in a list of CIDRs. This is done by specifying a `geo`[1] and a `map`[2] that work in conjunction to limit all of these requests together rather than treat them as separate ips.
[1] https://nginx.org/en/docs/http/ngx_http_geo_module.html
[2] https://nginx.org/en/docs/http/ngx_http_map_module.html
Bug: T400046
=> Add Alibaba DC ips to very tight rate limit

k8s/argocd/local/api.values.yaml, k8s/argocd/local/app-of-apps.values.yaml, k8s/argocd/production/api.values.yaml, k8s/argocd/staging/api.values.yaml, k8s/argocd/staging/app-of-apps.values.yaml, k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
https://phabricator.wikimedia.org/T388635
This does not deploy the new image yet but just adds the configuration values already.
- **add dsa complaint form conf values to envs**
- **prepare api chart 0.33.0 conf**
- **use api chart 0.33.0 on local/staging**
needs:
https://github.com/wbstack/charts/pull/195
=> Use api chart 0.33.0 on staging/local

k8s/argocd/local/api.values.yaml, k8s/argocd/local/app-of-apps.values.yaml, k8s/argocd/production/api.values.yaml, k8s/argocd/production/app-of-apps.values.yaml, k8s/argocd/staging/api.values.yaml, k8s/argocd/staging/app-of-apps.values.yaml, k8s/helmfile/env/local/api.values.yaml.gotmpl, k8s/helmfile/env/production/api.values.yaml.gotmpl, k8s/helmfile/env/staging/api.values.yaml.gotmpl
note: this just adds configuration values and does not reploy a new api image
depends on
* https://github.com/wbstack/charts/pull/195
* https://github.com/wmde/wbaas-deploy/pull/2188
- **use api chart 0.33.0 on production**
=> use api chart 0.33.0 on production

k8s/helmfile/env/production/ingress-nginx.values.yaml.gotmpl
Drop the limits to be even tighter. Allow no bursting and no delay. Also drop the limit to 1/s. This should cause us to drop most of these requests.
Bug: T400046
=> k8s: ingress-nginx make cloud zone limits super tight

Makefile, bin/local/install-ca-cert-firefox.sh, bin/local/new-local-cluster.sh, doc/local-dev-env.md
This adds a new script for local use that automatically installs the current minikube cluster CA certificate into your firefox profile. To make it work, you need to set the env var `FIREFOX_PROFILE` to your currently used firefox profile (a peek into `~/.mozilla/firefox` should reveal which is your the right one, probably the last one modified). Add it to your .envrc if you use [direnv](https://direnv.net/) or add it otherwise to your shell session, for example via the file `~/.profile`
- also this script runs now with new-cluster.sh, if env var is set
Use it via `./bin/local/install-ca-cert-firefox.sh` or simply `make local-ca-firefox`
=> local: helper script for firefox CA cert install

k8s/helmfile/helmfile.yaml
- We noticed the index.yaml file we used here still pointed to artifacts on bitnami servers: https://raw.githubusercontent.com/wbstack/bitnami-legacy/14b6efaa84c7ed5684885ca8d29479fe6e3ed973/bitnami/index.yaml
- We packaged the affected charts and uploaded them as releases here https://github.com/wbstack/bitnami-legacy/releases
- Discussion: https://mattermost.wikimedia.de/swe/pl/smgair3ccpnzfbzqhw665ifyte
Bug: T405468
=> fix: bitnami chart URLs
